/**
 * Parse `\newlabel` entries out of a LaTeX `.aux` file, and read+filter them for `pdf_geometry`'s
 * "floats" index.
 *
 * This file is document-controlled: an `.aux` is generated by the LaTeX run, but its content
 * (label keys, printed numbers) ultimately comes from the document's own `\label`/`\ref` macros
 * and packages, so it must be treated the same way CLAUDE.md treats a compile log — never opened,
 * resolved, stat'd, or otherwise acted on as a path, and never interpolated into a shell command.
 * It is parsed into plain strings and returned as plain strings, nothing more. It also means a
 * malformed or hand-crafted `.aux` must never cost more than a small, constant amount of work per
 * `\newlabel` marker it contains — see `MAX_GROUP_SCAN`/`GROUP_SKIP_SCAN`/`PARSE_BOUND` below.
 */

import { readFile } from 'node:fs/promises';
import { buildAuxPath } from '../services/compiler.js';
import { toPosix } from './paths.js';

export interface AuxLabel {
  label: string;
  /** The float's printed number, e.g. "3" or "2.1" — whatever \newlabel's first group holds. */
  number: string;
  /** The printed page the label resolved to, as it appears in the .aux (may be "iv", "3"). */
  page: string;
}

const DEFAULT_MAX_LABELS = 2000;
const MAX_FIELD_LENGTH = 200;
const NEWLABEL_MARKER = '\\newlabel';

/**
 * How far `readBraceGroup` will scan looking for a matching `}` before giving up on an unbalanced
 * `{`, and — separately — the length past which a group is treated as "too long to accept",
 * even once found (see `GROUP_SKIP_SCAN` below for the distinction). A real `\newlabel` group —
 * even hyperref's five-group form with a caption in the third slot — is at most a few hundred
 * characters; 4096 is generous headroom above that. Without a bound at all, an unbalanced `{`
 * (truncated file, or a hostile one) makes a single failing `readBraceGroup` call scan to
 * end-of-string: with `PARSE_BOUND`-many markers to try, that is O(n) work on EVERY failing
 * marker, i.e. O(n^2) overall (measured: 520KB of unbalanced markers took 27s). Capping the scan
 * turns each marker's worst case into O(MAX_GROUP_SCAN) — a constant — so the whole file is O(n)
 * regardless of how it is malformed. Exported so a test can build inputs that land exactly on the
 * accept/drop boundary rather than duplicating this magic number.
 */
export const MAX_GROUP_SCAN = 4096;

/**
 * A second, larger scan budget used ONLY to locate — never to accept — the true end of a group
 * whose content exceeds `MAX_GROUP_SCAN`. Why this exists: "always advance past an abandoned
 * group" (see `scanAuxEntries` below) is not safe if "abandoned" only means "past
 * `MAX_GROUP_SCAN`" — a real hyperref caption can clear `MAX_GROUP_SCAN` by a modest margin
 * (measured: a 4200-character caption lands about 180 characters past it), and advancing only to
 * `MAX_GROUP_SCAN`'s own limit resumes the scan partway through the group's own content, right in
 * reach of any `\newlabel`-shaped text still inside it — reintroducing the exact fabricated-entry
 * bug this whole mechanism exists to prevent. `GROUP_SKIP_SCAN` gives the scanner room to find
 * that group's real closing brace (so it can jump cleanly past everything inside it, including a
 * `\newlabel`-shaped substring) without ever accepting the group's content as a parsed entry —
 * length is still checked against `MAX_GROUP_SCAN` for that decision, so a well-formed-but-long
 * group is still reported as `dropped` (see `AuxFloatsResult`), never silently parsed past the
 * accepted length, and never silently lost either.
 *
 * Still a FIXED constant, so the linearity guarantee is untouched: a group whose true end is
 * never found even within `GROUP_SKIP_SCAN` (`readGroupOrSkip`'s `'exhausted'`) costs at most
 * `MAX_GROUP_SCAN + GROUP_SKIP_SCAN` — still O(1) per marker, regardless of `aux.length`. Whether
 * `scanAuxEntries` advances `searchFrom` past that outcome depends on WHY it failed
 * (`readGroupOrSkip`'s own doc has the detail): when the retry itself ran off the true end of the
 * file (`reason: 'truncated'`), it does not — there is nothing left to find, so leaving
 * `searchFrom` alone risks nothing and forgoes nothing. When the retry was itself budget-exhausted
 * (`reason: 'tooLong'`, more of the file remains beyond `GROUP_SKIP_SCAN`), it DOES advance, to
 * exactly as far as this call already scanned (`start + GROUP_SKIP_SCAN`) — not a guess, since
 * every character up to there was read looking for the closing brace. Total work across a whole
 * file stays bounded by `PARSE_BOUND * (MAX_GROUP_SCAN + GROUP_SKIP_SCAN)` — a small constant —
 * never by the number of markers squared, regardless of which of the two paths above is taken.
 */
const GROUP_SKIP_SCAN = MAX_GROUP_SCAN * 4;

/**
 * Hard cap on how many `\newlabel` markers a single scan (`parseAuxLabels` or `readAuxFloats`)
 * will ever inspect, enforced by a loop counter that is INDEPENDENT of how many entries parse
 * successfully — unlike the old `while (results.length < maxLabels)` guard, which only advanced
 * on a successful parse, so a file that is mostly failing markers never made progress toward its
 * own bound. Each marker's own cost is already bounded by `MAX_GROUP_SCAN`/`GROUP_SKIP_SCAN`
 * above, so this is a second, independent line of defense: even at the worst case (every marker
 * unbalanced, every group scan burning its full budget), total work is bounded by
 * `PARSE_BOUND * (MAX_GROUP_SCAN + GROUP_SKIP_SCAN)` — a constant, not something that grows with
 * file size. 50000 is well above any real document: `readAuxFloats`'s `total`/`omitted` (see
 * `AuxFloatsResult`) are exact against the TRUE count of `\newlabel` markers in the file as long
 * as the file contains at most this many; past it, both saturate at what this bound allows, same
 * as any bounded scan must — the module doc comment above is why a bound exists at all. Exported
 * so a test can exercise the exact boundary rather than duplicating a magic number that could
 * silently drift out of sync.
 */
export const PARSE_BOUND = 50_000;

/**
 * A brace-balanced reader over `s` starting just after an opening `{` at `start` (i.e. `s[start]`
 * must be `{`). On success, returns the group's raw content (excluding the outer braces) and the
 * index just past the matching closing `}`. On failure, reports WHY, because the two reasons
 * demand different handling from the caller (see `readGroupOrSkip`/`scanAuxEntries` below):
 * `'unbalanced'` means the scan reached the true end of `s` (or of the caller-supplied window)
 * without ever balancing — a truncated or malformed marker, and there is nothing more to find no
 * matter how far we looked; `'budgetExhausted'` means the scan hit `maxScan` characters with MORE
 * of `s` still unscanned — the group may still be perfectly well-formed, just longer than this
 * call was willing to accept. `scannedTo` is the index the scan actually reached, either way.
 */
function readBraceGroup(
  s: string,
  start: number,
  maxScan: number,
):
  | { kind: 'ok'; content: string; end: number }
  | { kind: 'fail'; reason: 'unbalanced' | 'budgetExhausted'; scannedTo: number } {
  if (s[start] !== '{') {
    return { kind: 'fail', reason: 'unbalanced', scannedTo: start };
  }
  let depth = 0;
  let i = start;
  const limit = Math.min(s.length, start + maxScan);
  for (; i < limit; i++) {
    const ch = s[i];
    if (ch === '\\') {
      // Skip an escaped character (e.g. `\{`, `\}`) so it never perturbs the brace count.
      i++;
      continue;
    }
    if (ch === '{') {
      depth++;
    } else if (ch === '}') {
      depth--;
      if (depth === 0) {
        return { kind: 'ok', content: s.slice(start + 1, i), end: i + 1 };
      }
    }
  }
  // Ran out of scan room without balancing. `limit < s.length` means more of `s` remains beyond
  // where we gave up — this call's budget was the limiting factor, not the input itself.
  const reason = limit < s.length ? 'budgetExhausted' : 'unbalanced';
  return { kind: 'fail', reason, scannedTo: limit };
}

/**
 * Wraps `readBraceGroup` for the two call sites (the key group, the outer group) that read
 * directly off the full `.aux` text rather than off an already-bounded slice of it, so a group
 * longer than `MAX_GROUP_SCAN` can still be found — and safely skipped past — rather than left to
 * wedge the scan in place or (worse) leave `\newlabel`-shaped text inside it discoverable as a
 * second, fabricated marker. See `GROUP_SKIP_SCAN`'s doc for why the retry is required, not
 * optional, and why it does not reintroduce the quadratic behavior `MAX_GROUP_SCAN` exists to
 * prevent.
 *
 * - `'ok'`: closed within `MAX_GROUP_SCAN` — an ordinary, acceptable group.
 * - `'tooLong'`: did NOT close within `MAX_GROUP_SCAN`, but did close within the larger
 *   `GROUP_SKIP_SCAN` retry — a well-formed group, just longer than we accept. `end` is its TRUE
 *   end, so the caller can jump cleanly past all of it (including anything `\newlabel`-shaped
 *   inside), never just past the smaller budget's own limit.
 * - `'unbalanced'`: the ORDINARY (`MAX_GROUP_SCAN`) attempt ran off the true end of `s` without
 *   balancing — genuinely truncated/malformed, not merely long. No retry is attempted: there is
 *   provably no closing brace left to find, and (this is the part that matters) the caller must
 *   NOT advance past this failure — text immediately after may still hold an entirely separate,
 *   legitimate `\newlabel` marker of its own (this is `parseAuxLabels`'s long-standing contract
 *   for a truncated file, and existing callers/tests depend on it).
 * - `'exhausted'`: the ordinary attempt was budget-exhausted (more of `s` remained) AND the
 *   `GROUP_SKIP_SCAN` retry ALSO failed to find a closing brace. Its true end is genuinely
 *   unknown, but WHY the retry failed still matters, so this carries its own `reason`:
 *     - `reason: 'truncated'` — the retry itself ran off the true end of `s` without balancing.
 *       Exactly like the ordinary `'unbalanced'` case, just discovered later: there is provably
 *       nothing more to find, so the caller must not "advance" past it (there is nothing there to
 *       skip past).
 *     - `reason: 'tooLong'` — the retry was ITSELF budget-exhausted (more of `s` remains beyond
 *       `GROUP_SKIP_SCAN`). The group's true end is still unknown, but every character up to
 *       `scannedTo` (`start + GROUP_SKIP_SCAN`) WAS linearly read for brace-balance, so nothing in
 *       `[start, scannedTo)` is unexplored text — advancing the search there (rather than leaving
 *       it at `start`) skips only text this call already looked at, never a guess. See
 *       `scanAuxEntries`'s own doc for how the two are used differently.
 */
function readGroupOrSkip(
  s: string,
  start: number,
):
  | { kind: 'ok'; content: string; end: number }
  | { kind: 'tooLong'; content: string; end: number }
  | { kind: 'unbalanced' }
  | { kind: 'exhausted'; reason: 'truncated' | 'tooLong'; scannedTo: number } {
  const primary = readBraceGroup(s, start, MAX_GROUP_SCAN);
  if (primary.kind === 'ok') {
    return primary;
  }
  if (primary.reason === 'unbalanced') {
    return { kind: 'unbalanced' };
  }
  const retry = readBraceGroup(s, start, GROUP_SKIP_SCAN);
  if (retry.kind === 'ok') {
    return { kind: 'tooLong', content: retry.content, end: retry.end };
  }
  return {
    kind: 'exhausted',
    reason: retry.reason === 'unbalanced' ? 'truncated' : 'tooLong',
    scannedTo: retry.scannedTo,
  };
}

/** Skip whitespace (including newlines — a `\newlabel` can be wrapped across lines) from `i`. */
function skipWs(s: string, i: number): number {
  let j = i;
  while (j < s.length && /\s/.test(s[j] ?? '')) j++;
  return j;
}

/**
 * One marker's outcome from `scanAuxEntries`: either a successfully-parsed entry, or a specific,
 * countable reason it was dropped. Every OTHER failure — a missing/unbalanced key group, an
 * outer group that is truly unbalanced (not merely long), or a missing number/page group — stays
 * a silent skip, exactly as `parseAuxLabels`'s contract has always been for a malformed marker:
 * there is no real, located label to report in those cases. `'dropped'` covers the cases where we
 * DO have a real, located label but no valid `AuxLabel` to report for the entry as a whole:
 *   - `reason: 'fieldTooLong'` — the whole entry parsed cleanly, but label, number or page
 *     exceeded the per-field length cap (`MAX_FIELD_LENGTH`).
 *   - `reason: 'groupTooLong'` — the KEY parsed normally (short enough to accept), but the outer
 *     group (holding number/page/caption) exceeded `MAX_GROUP_SCAN` before a matching `}` was
 *     found. Its true end may have been LOCATED via the `GROUP_SKIP_SCAN` retry
 *     (`readGroupOrSkip`'s `'tooLong'`) or not even that (`'exhausted'`) — either way there is no
 *     usable number/page, but the label itself is real and known, so `label` carries it.
 *   - `reason: 'keyTooLong'` — the KEY group itself exceeded `MAX_GROUP_SCAN`, located only via
 *     the `GROUP_SKIP_SCAN` retry (`readGroupOrSkip`'s `'tooLong'` on the key). There is no
 *     genuinely usable label here (an implausible multi-KB key is not a real label), but its
 *     literal text is still reported as `label` — same as `keyGroup.content` is used for
 *     `'groupTooLong'` — purely so a cleveref `@cref`-suffixed key (implausible, but not
 *     impossible to craft) is still excluded from the count the same way an ordinary one is; see
 *     `scanAuxEntries` for where this is produced.
 * All three are countable — see `AuxFloatsResult.dropped` — because in every one of them there IS
 * a real `\newlabel` marker the caller is choosing not to report, which is a different thing from
 * a marker that never parsed at all (a key or outer group that never closes at all, e.g. inside a
 * truncated file, has no located label to report and stays a silent skip, same as always).
 */
type ScanOutcome =
  | { kind: 'entry'; entry: AuxLabel }
  | { kind: 'dropped'; label: string; reason: 'fieldTooLong' | 'groupTooLong' | 'keyTooLong' };

/**
 * The shared scan behind both `parseAuxLabels` and `readAuxFloats`: walks `aux` for `\newlabel`
 * markers, yielding one outcome per marker that gets far enough to read a key group. Bounded on
 * two independent axes (see `MAX_GROUP_SCAN`/`GROUP_SKIP_SCAN`/`PARSE_BOUND` above) so total work
 * is linear in `aux.length` no matter how the file is malformed — none of these bounds depend on
 * how many outcomes the caller actually consumes, so a caller that stops early (`parseAuxLabels`,
 * once it has `maxLabels` entries) does strictly less work, never more.
 *
 * Advances `searchFrom` past a group's end WHENEVER that end is actually known, never on a guess:
 *   - `'ok'`/`'tooLong'` (either the key or the outer group): the marker has consumed that whole
 *     span either way, so re-entering it would let a `\newlabel`-shaped string INSIDE it (e.g. in
 *     hyperref's caption group, or even inside an implausibly long key) be picked up as a second,
 *     fabricated entry — so `searchFrom` always jumps to (at least) the key's own end the moment
 *     the key is located, and to the outer group's end once that is located too.
 *   - `'exhausted'` with `reason: 'tooLong'`: the group's true end is still unknown, but
 *     `readGroupOrSkip` already linearly scanned every character up to `scannedTo`
 *     (`start + GROUP_SKIP_SCAN`) looking for it — so advancing `searchFrom` there is NOT a guess
 *     either, it only skips text this call already read. This closes the fabrication risk for any
 *     `\newlabel`-shaped substring located anywhere within that scanned span, not merely near its
 *     start — before this, not advancing at all left the WHOLE remaining group vulnerable
 *     regardless of where inside it a fake marker sat. A fake beyond `GROUP_SKIP_SCAN` characters
 *     into the group is a residual this cannot close (its position is never scanned at all), but
 *     that is now the full extent of the risk: a `\newlabel`-shaped string appearing more than
 *     `GROUP_SKIP_SCAN` (16384) characters into a single still-unclosed group.
 *   - `'exhausted'` with `reason: 'truncated'`, or plain `'unbalanced'`: the retry (or the primary
 *     attempt) ran off the TRUE end of `aux` without ever finding a closing brace — there is
 *     provably nothing left to find no matter how far we looked, so `searchFrom` is left wherever
 *     it already is (which may still be past the key, if the key itself was located). This is
 *     `parseAuxLabels`'s long-standing contract for a truncated file: text immediately after a
 *     genuinely unbalanced group may still hold an entirely separate, legitimate `\newlabel` of
 *     its own, and an existing test depends on it not being skipped over.
 *
 * Every `readGroupOrSkip` call is itself O(1)-bounded regardless of outcome, so none of this
 * touches the linearity guarantee — it only decides, per outcome, exactly how far it is SAFE to
 * jump, never whether to.
 */
function* scanAuxEntries(aux: string): Generator<ScanOutcome> {
  let searchFrom = 0;
  let scans = 0;
  while (scans < PARSE_BOUND) {
    const markerIdx = aux.indexOf(NEWLABEL_MARKER, searchFrom);
    if (markerIdx === -1) {
      break;
    }
    scans++;
    // Advance past this marker regardless of what happens below, so a malformed entry cannot
    // wedge the scan in place.
    searchFrom = markerIdx + NEWLABEL_MARKER.length;

    let i = skipWs(aux, searchFrom);
    const keyGroup = readGroupOrSkip(aux, i);
    if (keyGroup.kind === 'unbalanced') {
      continue;
    }
    if (keyGroup.kind === 'exhausted') {
      if (keyGroup.reason === 'tooLong') {
        // Not a guess — scannedTo is exactly how far this call already read; see this function's
        // own doc for why that makes advancing here safe rather than a risk.
        searchFrom = keyGroup.scannedTo;
      }
      // reason 'truncated': genuinely ran off the true end of the file — nothing more to find, so
      // leave searchFrom where it is, same contract as the plain 'unbalanced' case below.
      continue;
    }

    // keyGroup is 'ok' or 'tooLong' — either way its end is real and known, so it is always safe
    // to resume from there even if everything that follows (the outer group) turns out malformed.
    const keyTooLong = keyGroup.kind === 'tooLong';
    const keyContent = keyGroup.content;
    searchFrom = keyGroup.end;

    i = skipWs(aux, keyGroup.end);
    const outerGroup = readGroupOrSkip(aux, i);
    if (outerGroup.kind === 'unbalanced') {
      // Truly no closing brace anywhere in the rest of the file for this group. searchFrom stays
      // at the key's own (already-known-safe) end from above; nothing further is known.
      continue;
    }
    if (outerGroup.kind === 'exhausted') {
      if (outerGroup.reason === 'tooLong') {
        searchFrom = outerGroup.scannedTo;
      }
      // reason 'truncated': stays at keyGroup.end, same reasoning as the key's own case above.
      //
      // The key DID parse — there is a real label here — so this is no longer a silent skip: the
      // caller gets a countable 'dropped' outcome instead of the entry simply vanishing.
      yield {
        kind: 'dropped',
        label: keyContent,
        reason: keyTooLong ? 'keyTooLong' : 'groupTooLong',
      };
      continue;
    }
    if (outerGroup.kind === 'tooLong') {
      // A well-formed \newlabel whose outer group is longer than MAX_GROUP_SCAN accepts. We
      // found its TRUE end via the GROUP_SKIP_SCAN retry, so jump cleanly past the whole group —
      // including anything \newlabel-shaped inside it — instead of resuming partway through it.
      searchFrom = outerGroup.end;
      yield {
        kind: 'dropped',
        label: keyContent,
        reason: keyTooLong ? 'keyTooLong' : 'groupTooLong',
      };
      continue;
    }
    // outerGroup.kind === 'ok'. The whole outer group has been consumed either way (success or a
    // downstream field-shape failure below) — jump past it so nothing inside it is ever
    // re-entered as its own marker.
    searchFrom = outerGroup.end;

    if (keyTooLong) {
      // Both groups are now fully located and consumed cleanly, but the key itself was never a
      // usable label (see the ScanOutcome doc for what `keyContent` holds and why it is still
      // worth reporting).
      yield { kind: 'dropped', label: keyContent, reason: 'keyTooLong' };
      continue;
    }

    // The outer group's content starts with two brace groups: {number}{page}[...]. Read them with
    // the same balanced reader, ignoring anything after (hyperref appends {\relax }{anchor}{}).
    // This content is already bounded to at most MAX_GROUP_SCAN characters (outerGroup succeeded
    // under that budget to get here), so these two reads can never themselves hit a scan budget —
    // only genuine unbalance is possible, and that stays a silent skip as it always has.
    const inner = outerGroup.content;
    let j = skipWs(inner, 0);
    const numberGroup = readBraceGroup(inner, j, MAX_GROUP_SCAN);
    if (numberGroup.kind !== 'ok') {
      continue;
    }
    j = skipWs(inner, numberGroup.end);
    const pageGroup = readBraceGroup(inner, j, MAX_GROUP_SCAN);
    if (pageGroup.kind !== 'ok') {
      continue;
    }

    const label = keyContent;
    const number = numberGroup.content;
    const page = pageGroup.content;
    if (
      label.length > MAX_FIELD_LENGTH ||
      number.length > MAX_FIELD_LENGTH ||
      page.length > MAX_FIELD_LENGTH
    ) {
      yield { kind: 'dropped', label, reason: 'fieldTooLong' };
      continue;
    }

    yield { kind: 'entry', entry: { label, number, page } };
  }
}

export function parseAuxLabels(aux: string, opts?: { maxLabels?: number }): AuxLabel[] {
  const maxLabels = opts?.maxLabels ?? DEFAULT_MAX_LABELS;
  const results: AuxLabel[] = [];

  for (const outcome of scanAuxEntries(aux)) {
    if (outcome.kind !== 'entry') {
      continue;
    }
    results.push(outcome.entry);
    if (results.length >= maxLabels) {
      break;
    }
  }

  return results;
}

/** `pdf_geometry`'s "floats" cap — labels past this are reported as `omitted`, never silently. */
export const DEFAULT_MAX_FLOATS = 200;

/**
 * cleveref's internal shadow records: for every `\label{x}` it also writes `\newlabel{x@cref}`
 * whose "number"/"page" fields are its own bracketed cross-reference codes (e.g.
 * `[figure][1][]1` / `[1][1][]1`), not printed page numbers at all. Verified against a real
 * `pdflatex` + cleveref run (this repo's own tex install, cleveref's `\newlabel` macros in
 * cleveref.sty around `\cref@constructprefix`/`\@newl@bel`): the only shadow suffix cleveref
 * emits is `@cref` — no separate `@cref@...` sibling was found. `parseAuxLabels` itself stays
 * faithful to the file and returns these; filtering them out of the "floats" index happens here,
 * one layer up, so a caller of the pure parser still sees exactly what the `.aux` says.
 */
const CLEVEREF_SHADOW_SUFFIXES = ['@cref'];

function isCleverefShadow(label: string): boolean {
  return CLEVEREF_SHADOW_SUFFIXES.some((suffix) => label.endsWith(suffix));
}

export interface AuxFloatsResult {
  /** Real (non-shadow) labels, capped at `opts.max` (default DEFAULT_MAX_FLOATS). */
  floats: AuxLabel[];
  /** Real labels found past the `max` cap — `total - floats.length`. Exact (computed against the
   *  TRUE total in `total`, not a smaller parse-time cutoff) as long as the file contains at most
   *  `PARSE_BOUND` `\newlabel` markers; see `total`'s doc for what happens past that. */
  omitted: number;
  /** The true count of real (non-shadow), successfully-parsed labels found in the file — i.e.
   *  `floats.length + omitted`, before the `max` cap is applied. A label counted here always has
   *  a valid `AuxLabel` behind it; one dropped for an over-length field or an over-budget group
   *  (see `dropped` below) is deliberately excluded, the same way it always has been for the
   *  former. Exact for any file with at most `PARSE_BOUND` `\newlabel` markers (shadow entries
   *  included in that count, since every marker costs a scan regardless of what it turns out to
   *  be) — a document with more markers than that is far past anything real, and both `total` and
   *  `omitted` saturate at whatever `PARSE_BOUND` allowed rather than reflecting the file's actual
   *  count. */
  total: number;
  /** Real (non-shadow) `\newlabel` entries found but dropped because there was no valid
   *  `AuxLabel` to report for them — never included in `total` or `floats` either way, counted
   *  here instead so the drop is never silent. Three distinct causes land in this one count (see
   *  `ScanOutcome`'s doc for the exact mechanics of each): a field (label, number, or page)
   *  exceeded the per-field length cap (`MAX_FIELD_LENGTH`) after the entry otherwise parsed
   *  cleanly; the entry's outer group (holding number/page/caption) exceeded the `MAX_GROUP_SCAN`
   *  scan budget before a matching `}` was found, whether or not its true end was ever located;
   *  or the KEY itself exceeded `MAX_GROUP_SCAN` before a matching `}` was found for IT. All three
   *  are, from a caller's point of view, the same fact: "there was a real `\newlabel` marker here
   *  we could not give you a usable entry for." */
  dropped: number;
  /** Present only when no `.aux` was found in the build directory. */
  note?: string;
}

/**
 * Read and parse the build-dir `.aux` for a project/root file, for `pdf_geometry`'s "floats" kind.
 * Never throws for a missing `.aux` (nothing compiled yet, or a backend that doesn't write one) —
 * that comes back as `{ floats: [], omitted: 0, total: 0, dropped: 0, note }`. Any other read
 * failure (e.g. unreadable permissions) propagates, since that is a real problem the caller should
 * see, not a normal "not compiled yet" state.
 */
export async function readAuxFloats(
  projectDir: string,
  rootFile: string,
  opts?: { max?: number },
): Promise<AuxFloatsResult> {
  const max = opts?.max ?? DEFAULT_MAX_FLOATS;
  const auxPath = buildAuxPath(projectDir, rootFile);

  let auxContent: string;
  try {
    auxContent = await readFile(auxPath, 'utf8');
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
      return {
        floats: [],
        omitted: 0,
        total: 0,
        dropped: 0,
        note:
          `No .aux found in the build directory (${toPosix(auxPath)}) — nothing has been ` +
          'compiled with this root file yet, or the compile backend in use did not write one.',
      };
    }
    throw err;
  }

  // A single pass over the whole file (bounded per MAX_GROUP_SCAN/GROUP_SKIP_SCAN/PARSE_BOUND
  // above, never per-result) rather than parseAuxLabels + a post-hoc filter, so `total` reflects
  // every real \newlabel in the file, not just the ones that fit under an earlier, smaller parse
  // cutoff.
  const floats: AuxLabel[] = [];
  let total = 0;
  let dropped = 0;
  for (const outcome of scanAuxEntries(auxContent)) {
    if (outcome.kind === 'dropped') {
      if (!isCleverefShadow(outcome.label)) {
        dropped++;
      }
      continue;
    }
    if (isCleverefShadow(outcome.entry.label)) {
      continue;
    }
    total++;
    if (floats.length < max) {
      floats.push(outcome.entry);
    }
  }

  return { floats, omitted: total - floats.length, total, dropped };
}
