/**
 * Parse `\newlabel` entries out of a LaTeX `.aux` file, and read+filter them for `pdf_geometry`'s
 * "floats" index.
 *
 * This file is document-controlled: an `.aux` is generated by the LaTeX run, but its content
 * (label keys, printed numbers) ultimately comes from the document's own `\label`/`\ref` macros
 * and packages, so it must be treated the same way CLAUDE.md treats a compile log — never opened,
 * resolved, stat'd, or otherwise acted on as a path, and never interpolated into a shell command.
 * It is parsed into plain strings and returned as plain strings, nothing more. The one name in
 * it that is followed at all — an `\@input{chap.aux}`, which is where `\include` puts each
 * chapter's labels — is still never used as a path: each of its components is a key looked up
 * in a directory listing of the (server-owned) build dir, one level at a time, so a name that
 * leaves the build dir, or passes through a link inside it, finds nothing (see
 * `findBuildDirAux`). It also means a
 * malformed or hand-crafted `.aux` must never cost more than a small, constant amount of work per
 * `\newlabel` marker it contains — see `MAX_GROUP_SCAN`/`GROUP_SKIP_SCAN`/`PARSE_BOUND` below.
 */

import type { Dirent } from 'node:fs';
import { constants as fsConstants } from 'node:fs';
import { lstat, open, readdir, readFile, realpath } from 'node:fs/promises';
import path from 'node:path';
import { buildAuxPath, buildAuxPathIn } from '../services/compiler.js';
import { MAX_READ_BYTES } from '../services/fileService.js';
import { unwrapLines } from '../services/logParser.js';
import { toPosix } from './paths.js';

export interface AuxLabel {
  label: string;
  /** The float's printed number, e.g. "3" or "2.1" — whatever \newlabel's first group holds. */
  number: string;
  /** The printed page the label resolved to, as it appears in the .aux (may be "iv", "3"). */
  page: string;
}

const DEFAULT_MAX_LABELS = 2000;
const MAX_FIELD_LENGTH = 200;
const NEWLABEL_MARKER = '\\newlabel';

/**
 * How far `readBraceGroup` will scan looking for a matching `}` before giving up on an unbalanced
 * `{`, and — separately — the length past which a group is treated as "too long to accept",
 * even once found (see `GROUP_SKIP_SCAN` below for the distinction). A real `\newlabel` group —
 * even hyperref's five-group form with a caption in the third slot — is at most a few hundred
 * characters; 4096 is generous headroom above that. Without a bound at all, an unbalanced `{`
 * (truncated file, or a hostile one) makes a single failing `readBraceGroup` call scan to
 * end-of-string: with `PARSE_BOUND`-many markers to try, that is O(n) work on EVERY failing
 * marker, i.e. O(n^2) overall (measured: 520KB of unbalanced markers took 27s). Capping the scan
 * turns each marker's worst case into O(MAX_GROUP_SCAN) — a constant — so the whole file is O(n)
 * regardless of how it is malformed. Exported so a test can build inputs that land exactly on the
 * accept/drop boundary rather than duplicating this magic number.
 */
export const MAX_GROUP_SCAN = 4096;

/**
 * A second, larger scan budget used ONLY to locate — never to accept — the true end of a group
 * whose content exceeds `MAX_GROUP_SCAN`. Why this exists: "always advance past an abandoned
 * group" (see `scanAuxEntries` below) is not safe if "abandoned" only means "past
 * `MAX_GROUP_SCAN`" — a real hyperref caption can clear `MAX_GROUP_SCAN` by a modest margin
 * (measured: a 4200-character caption lands about 180 characters past it), and advancing only to
 * `MAX_GROUP_SCAN`'s own limit resumes the scan partway through the group's own content, right in
 * reach of any `\newlabel`-shaped text still inside it — reintroducing the exact fabricated-entry
 * bug this whole mechanism exists to prevent. `GROUP_SKIP_SCAN` gives the scanner room to find
 * that group's real closing brace (so it can jump cleanly past everything inside it, including a
 * `\newlabel`-shaped substring) without ever accepting the group's content as a parsed entry —
 * length is still checked against `MAX_GROUP_SCAN` for that decision, so a well-formed-but-long
 * group is still reported as `dropped` (see `AuxFloatsResult`), never silently parsed past the
 * accepted length, and never silently lost either.
 *
 * Still a FIXED constant, so the linearity guarantee is untouched: a group whose true end is
 * never found even within `GROUP_SKIP_SCAN` (`readGroupOrSkip`'s `'exhausted'`) costs at most
 * `MAX_GROUP_SCAN + GROUP_SKIP_SCAN` — still O(1) per marker, regardless of `aux.length`. Whether
 * `scanAuxEntries` advances `searchFrom` past that outcome depends on WHY it failed
 * (`readGroupOrSkip`'s own doc has the detail): when the retry itself ran off the true end of the
 * file (`reason: 'truncated'`), it does not — there is nothing left to find, so leaving
 * `searchFrom` alone risks nothing and forgoes nothing. It does still open an `OpenSpan` there
 * (see `scanAuxEntries`), which costs nothing and is not an advance: a walk that reached
 * end-of-file without the depth ever touching 0 has PROVEN the group is open at every position
 * after `start`, so every later marker is inside it. When the retry was itself budget-exhausted
 * (`reason: 'tooLong'`, more of the file remains beyond `GROUP_SKIP_SCAN`), it DOES advance, to
 * exactly as far as this call already scanned (`start + GROUP_SKIP_SCAN`) — not a guess, since
 * every character up to there was read looking for the closing brace. Total work across a whole
 * file stays bounded by `PARSE_BOUND * (MAX_GROUP_SCAN + GROUP_SKIP_SCAN)` — a small constant —
 * never by the number of markers squared, regardless of which of the two paths above is taken.
 *
 * Advancing to `start + GROUP_SKIP_SCAN` is where this constant stops being enough on its own,
 * and why `scanAuxEntries` also keeps an OPEN SPAN (see `OpenSpan` below) for the `'tooLong'`
 * case. Jumping there says nothing about the text BEYOND it: the group is still open, so a
 * `\newlabel`-shaped string sitting further inside it than this budget reaches is the next thing
 * `indexOf` finds, and used to be reported as a real label — issue #80 §3. Raising the constant
 * only moves that boundary; nothing finite removes it. What removes it is continuing the same
 * brace walk past the budget, one stretch at a time, and that is what the open span does.
 *
 * Exported for the same reason `MAX_GROUP_SCAN` is: so a test can build an input that lands
 * exactly on this boundary rather than re-deriving the number and silently drifting off it.
 */
export const GROUP_SKIP_SCAN = MAX_GROUP_SCAN * 4;

/**
 * Hard cap on how many `\newlabel` markers a single scan (`parseAuxLabels` or `readAuxFloats`)
 * will ever inspect, enforced by a loop counter that is INDEPENDENT of how many entries parse
 * successfully — unlike the old `while (results.length < maxLabels)` guard, which only advanced
 * on a successful parse, so a file that is mostly failing markers never made progress toward its
 * own bound. Each marker's own cost is already bounded by `MAX_GROUP_SCAN`/`GROUP_SKIP_SCAN`
 * above, so this is a second, independent line of defense: even at the worst case (every marker
 * unbalanced, every group scan burning its full budget), total work is bounded by
 * `PARSE_BOUND * (MAX_GROUP_SCAN + GROUP_SKIP_SCAN)` — a constant, not something that grows with
 * file size. 50000 is well above any real document: `readAuxFloats`'s `total`/`omitted` (see
 * `AuxFloatsResult`) are exact against the TRUE count of `\newlabel` markers in the file as long
 * as the file contains at most this many; past it, both saturate at what this bound allows, same
 * as any bounded scan must — the module doc comment above is why a bound exists at all. Exported
 * so a test can exercise the exact boundary rather than duplicating a magic number that could
 * silently drift out of sync.
 */
export const PARSE_BOUND = 50_000;

/**
 * A scan-work accumulator: the number of CHARACTERS of `aux` this scan has looked at — every
 * character the `indexOf` pass walks over on its way to a marker, every character a brace walk
 * (`scanBalance`) steps through, and every character `skipWs` runs past. It exists for exactly one
 * reason: the guarantee this whole module is built around is that total work stays LINEAR in
 * `aux.length` no matter how the file is malformed, and a test can only hold that guarantee by
 * measuring the work. Measuring it with `Date.now()` was tried first and flaked — at the input
 * sizes these bounds make cheap, a single-digit-millisecond sample is dominated by scheduler
 * jitter and GC from the rest of a parallel test run, so a genuinely linear scan read 3.2x while
 * the threshold separating linear (~2x) from quadratic (~4x) sat at 3.0 (issue #173). A character
 * count is exactly the quantity those bounds bound, is identical on every machine and under any
 * load, and is inflated precisely by the mistake being guarded against: re-walking a group from
 * its start for every marker reads the same characters over and over, and the counter says so.
 *
 * It is threaded as an optional parameter and is `undefined` on every production path — the only
 * way to obtain one is `measureAuxScanWork`, a separate export that no ordinary caller reaches, so
 * there is no option a caller of `parseAuxLabels`/`readAuxFloats` could leave switched on. Nothing
 * here logs (stdout is the JSON-RPC channel, and this would not even earn a stderr line); it only
 * adds to a number. Counting is done by arithmetic at each scan's exit (`i - from`), never a
 * per-character increment, so the hot loops keep their shape whether or not one is passed.
 */
interface ScanWork {
  /** Characters examined so far. Monotonically increasing; never reset mid-scan. */
  steps: number;
}

/**
 * The one home of the brace-balance rules — `{` opens, `}` closes, and a backslash escapes
 * whatever follows it so a literal `\{`/`\}` never perturbs the count — factored out of
 * `readBraceGroup` so a walk can be RESUMED rather than restarted. `readBraceGroup` runs it over
 * one budgeted window; `scanAuxEntries` continues that very same walk over the text after a
 * window that ran out (see `OpenSpan`). Two properties make resuming safe and cheap, and both
 * come from this being one function rather than two implementations of the same rules:
 *
 * - `next` is the index to resume at, which is one PAST `to` when an escape straddled the
 *   boundary (the `\` was consumed at `to - 1`, so the character it escapes must not be re-read
 *   as a brace). A second, independent scanner would get this wrong in exactly the way that turns
 *   an escaped brace into a real one.
 * - `next` only ever moves forward, so continuing a walk reads each character of the file at most
 *   once no matter how many times it is continued.
 *
 * Scans `[from, to)` (clamped to `s.length`) starting at brace depth `depth`. `'closed'` means the
 * depth reached 0 and `end` is the index just past the closing `}`; `'open'` means the window ran
 * out first, and carries the state to pick the walk up again. An `'open'` depth is always >= 1: a
 * depth reaching 0 returns `'closed'` instead, and it can never step below 0 without passing
 * through it.
 */
function scanBalance(
  s: string,
  from: number,
  to: number,
  depth: number,
  work?: ScanWork,
): { kind: 'closed'; end: number } | { kind: 'open'; depth: number; next: number } {
  let d = depth;
  let i = from;
  const limit = Math.min(s.length, to);
  for (; i < limit; i++) {
    const ch = s[i];
    if (ch === '\\') {
      // Skip an escaped character (e.g. `\{`, `\}`) so it never perturbs the brace count.
      i++;
      continue;
    }
    if (ch === '{') {
      d++;
    } else if (ch === '}') {
      d--;
      if (d === 0) {
        if (work) work.steps += i + 1 - from;
        return { kind: 'closed', end: i + 1 };
      }
    }
  }
  if (work) work.steps += Math.max(0, i - from);
  return { kind: 'open', depth: d, next: i };
}

/**
 * A brace-balanced reader over `s` starting just after an opening `{` at `start` (i.e. `s[start]`
 * must be `{`). On success, returns the group's raw content (excluding the outer braces) and the
 * index just past the matching closing `}`. On failure, reports WHY, because the two reasons
 * demand different handling from the caller (see `readGroupOrSkip`/`scanAuxEntries` below):
 * `'unbalanced'` means the scan reached the true end of `s` (or of the caller-supplied window)
 * without ever balancing — a truncated or malformed marker, and there is nothing more to find no
 * matter how far we looked; `'budgetExhausted'` means the scan hit `maxScan` characters with MORE
 * of `s` still unscanned — the group may still be perfectly well-formed, just longer than this
 * call was willing to accept. `scannedTo` is the index the scan actually reached, either way, and
 * `depth`/`next` are the underlying walk's resume state (see `scanBalance`) so a caller that has
 * to keep tracking this group past the budget continues the same walk rather than starting a
 * second one over text it has already read.
 */
function readBraceGroup(
  s: string,
  start: number,
  maxScan: number,
  work?: ScanWork,
):
  | { kind: 'ok'; content: string; end: number }
  | {
      kind: 'fail';
      reason: 'unbalanced' | 'budgetExhausted';
      scannedTo: number;
      depth: number;
      next: number;
    } {
  if (s[start] !== '{') {
    return { kind: 'fail', reason: 'unbalanced', scannedTo: start, depth: 0, next: start };
  }
  const limit = Math.min(s.length, start + maxScan);
  const walk = scanBalance(s, start, limit, 0, work);
  if (walk.kind === 'closed') {
    return { kind: 'ok', content: s.slice(start + 1, walk.end - 1), end: walk.end };
  }
  // Ran out of scan room without balancing. `limit < s.length` means more of `s` remains beyond
  // where we gave up — this call's budget was the limiting factor, not the input itself.
  const reason = limit < s.length ? 'budgetExhausted' : 'unbalanced';
  return { kind: 'fail', reason, scannedTo: limit, depth: walk.depth, next: walk.next };
}

/**
 * Wraps `readBraceGroup` for the two call sites (the key group, the outer group) that read
 * directly off the full `.aux` text rather than off an already-bounded slice of it, so a group
 * longer than `MAX_GROUP_SCAN` can still be found — and safely skipped past — rather than left to
 * wedge the scan in place or (worse) leave `\newlabel`-shaped text inside it discoverable as a
 * second, fabricated marker. See `GROUP_SKIP_SCAN`'s doc for why the retry is required, not
 * optional, and why it does not reintroduce the quadratic behavior `MAX_GROUP_SCAN` exists to
 * prevent.
 *
 * - `'ok'`: closed within `MAX_GROUP_SCAN` — an ordinary, acceptable group.
 * - `'tooLong'`: did NOT close within `MAX_GROUP_SCAN`, but did close within the larger
 *   `GROUP_SKIP_SCAN` retry — a well-formed group, just longer than we accept. `end` is its TRUE
 *   end, so the caller can jump cleanly past all of it (including anything `\newlabel`-shaped
 *   inside), never just past the smaller budget's own limit.
 * - `'unbalanced'`: the ORDINARY (`MAX_GROUP_SCAN`) attempt ran off the true end of `s` without
 *   balancing — genuinely truncated/malformed, not merely long. No retry is attempted: there is
 *   provably no closing brace left to find, and the caller must NOT advance `searchFrom` past
 *   this failure, because nothing was located to advance TO. It carries `depth`/`next` anyway,
 *   and `depth` is the discriminator the caller needs:
 *     - `depth >= 1` — a `{` WAS opened at `start` and the walk proved it is still open at
 *       end-of-file (see `scanBalance`: a depth reaching 0 returns `'closed'`), so every marker
 *       after it is inside it and `scanAuxEntries` opens an `OpenSpan` to refuse them.
 *     - `depth === 0` — `s[start]` was not a `{` at all, so no group was ever opened. This says
 *       nothing whatever about the text that follows and must NEVER open a span.
 * - `'exhausted'`: the ordinary attempt was budget-exhausted (more of `s` remained) AND the
 *   `GROUP_SKIP_SCAN` retry ALSO failed to find a closing brace. Its true end is genuinely
 *   unknown, but WHY the retry failed still matters, so this carries its own `reason`:
 *     - `reason: 'truncated'` — the retry itself ran off the true end of `s` without balancing.
 *       Exactly like the ordinary `'unbalanced'` case above, just discovered later: there is
 *       provably nothing more to find, so the caller must not "advance" past it (there is nothing
 *       there to skip past) — and, on the same proof, it opens an `OpenSpan` just the same.
 *     - `reason: 'tooLong'` — the retry was ITSELF budget-exhausted (more of `s` remains beyond
 *       `GROUP_SKIP_SCAN`). The group's true end is still unknown, but every character up to
 *       `scannedTo` (`start + GROUP_SKIP_SCAN`) WAS linearly read for brace-balance, so nothing in
 *       `[start, scannedTo)` is unexplored text — advancing the search there (rather than leaving
 *       it at `start`) skips only text this call already looked at, never a guess. See
 *       `scanAuxEntries`'s own doc for how the two are used differently.
 *
 * `'exhausted'` and `'unbalanced'` both carry `depth`/`next`, the walk's resume state, and every
 * outcome that opens a group has a use for it. Under `'tooLong'` the group is still open at
 * `scannedTo` and the file continues past it, so `scanAuxEntries` keeps walking the SAME group
 * from there (see `OpenSpan`) rather than treating everything past the budget as text outside it.
 * Under `'truncated'` (and `'unbalanced'` with `depth >= 1`) the walk already reached the true end
 * of `s`, so `next` sits at end-of-file and the resumed walk is a no-op that can never close —
 * which is precisely the wanted answer, delivered at O(1) per later marker: the group is open
 * everywhere after `start`, so everything that follows is refused.
 */
function readGroupOrSkip(
  s: string,
  start: number,
  work?: ScanWork,
):
  | { kind: 'ok'; content: string; end: number }
  | { kind: 'tooLong'; content: string; end: number }
  | { kind: 'unbalanced'; depth: number; next: number }
  | {
      kind: 'exhausted';
      reason: 'truncated' | 'tooLong';
      scannedTo: number;
      depth: number;
      next: number;
    } {
  const primary = readBraceGroup(s, start, MAX_GROUP_SCAN, work);
  if (primary.kind === 'ok') {
    return primary;
  }
  if (primary.reason === 'unbalanced') {
    // depth/next are the walk's own state, and `depth` is what tells "a `{` was opened here and
    // never closes anywhere in `s`" (>= 1) from "there was no `{` here at all" (0). Only the
    // former is evidence about the text that follows.
    return { kind: 'unbalanced', depth: primary.depth, next: primary.next };
  }
  const retry = readBraceGroup(s, start, GROUP_SKIP_SCAN, work);
  if (retry.kind === 'ok') {
    return { kind: 'tooLong', content: retry.content, end: retry.end };
  }
  return {
    kind: 'exhausted',
    reason: retry.reason === 'unbalanced' ? 'truncated' : 'tooLong',
    scannedTo: retry.scannedTo,
    depth: retry.depth,
    next: retry.next,
  };
}

/**
 * A group `readGroupOrSkip` left OPEN: no scan budget found its closing brace. Two shapes reach
 * here, and both are carried the same way.
 *
 * - The file continues past where the retry gave up (`'exhausted'` + `reason: 'tooLong'`). The
 *   group MIGHT still close, so the walk is carried forward marker by marker to find out, and a
 *   marker after the close is parsed normally.
 * - The walk ran to the TRUE end of the file without the depth ever touching 0
 *   (`'exhausted'` + `reason: 'truncated'`, and plain `'unbalanced'` with `depth >= 1`). The group
 *   provably never closes, the carried walk is a no-op, and every later marker is refused.
 *
 * Either way it holds the brace walk's resume state, so `scanAuxEntries` can keep walking that
 * one group forward instead of guessing where it ends.
 *
 * Why this is needed at all: advancing `searchFrom` to `start + GROUP_SKIP_SCAN` protects only
 * the text the retry actually read. Everything past it is still inside the group, and a
 * `\newlabel`-shaped string there was the next thing `indexOf` found — reported as a real label,
 * off a `.aux` that is document-controlled, which `render_pages` would then resolve to a page and
 * render with confidence (issue #80 §3). It cannot be closed by skipping ahead: the group's end
 * is genuinely unknown, and skipping on a guess would swallow a legitimate separate `\newlabel`
 * in text nobody ever scanned. So the span is carried instead of jumped.
 *
 * Cost, which is the whole reason this is a resumable cursor and not a re-scan: the walk is
 * continued only as far as the NEXT marker, and `next` never moves backwards, so every character
 * of the file is walked at most once across all continuations — one extra linear pass at worst,
 * on top of the `indexOf` pass `scanAuxEntries` already makes. Continuing to end-of-file instead,
 * to prove up front whether the group ever closes, is the obvious alternative and is exactly the
 * quadratic blowup `MAX_GROUP_SCAN` exists to prevent (520KB of unbalanced markers took 27s of
 * blocked event loop inside `runExclusive`): each of `PARSE_BOUND`-many markers would pay a
 * scan over the whole remaining file.
 *
 * At most one span is ever open: it is set only on the branches that `continue` immediately, and
 * the next marker either closes it or is refused under it, so a new group is never read while one
 * is outstanding.
 */
interface OpenSpan {
  /** Brace depth the walk had reached at `next`. Always >= 1 — see `scanBalance`. */
  depth: number;
  /** Where to resume the walk; may be one past the budget when an escape straddled it. */
  next: number;
}

/** Skip whitespace (including newlines — a `\newlabel` can be wrapped across lines) from `i`. */
function skipWs(s: string, i: number, work?: ScanWork): number {
  let j = i;
  while (j < s.length && /\s/.test(s[j] ?? '')) j++;
  if (work) work.steps += j - i;
  return j;
}

/**
 * One marker's outcome from `scanAuxEntries`: a successfully-parsed entry, or one of three
 * countable ways it did not become one. Every OTHER failure — a `\newlabel` not followed by a
 * `{` at all, an outer group that is truly unbalanced (not merely long), or a missing
 * number/page group — stays a silent skip, exactly as `parseAuxLabels`'s contract has always
 * been for a malformed marker. `'dropped'` covers the cases where we DO have a real, located
 * label but no valid `AuxLabel` to report for the entry as a whole:
 *   - `reason: 'fieldTooLong'` — the whole entry parsed cleanly, but label, number or page
 *     exceeded the per-field length cap (`MAX_FIELD_LENGTH`).
 *   - `reason: 'groupTooLong'` — the KEY parsed normally (short enough to accept), but the outer
 *     group (holding number/page/caption) exceeded `MAX_GROUP_SCAN` before a matching `}` was
 *     found. Its true end may have been LOCATED via the `GROUP_SKIP_SCAN` retry
 *     (`readGroupOrSkip`'s `'tooLong'`) or not even that (`'exhausted'`) — either way there is no
 *     usable number/page, but the label itself is real and known, so `label` carries it.
 *   - `reason: 'keyTooLong'` — the KEY group itself exceeded `MAX_GROUP_SCAN`, located only via
 *     the `GROUP_SKIP_SCAN` retry (`readGroupOrSkip`'s `'tooLong'` on the key). There is no
 *     genuinely usable label here (an implausible multi-KB key is not a real label), but its
 *     literal text is still reported as `label` — same as `keyGroup.content` is used for
 *     `'groupTooLong'` — purely so a cleveref `@cref`-suffixed key (implausible, but not
 *     impossible to craft) is still excluded from the count the same way an ordinary one is; see
 *     `scanAuxEntries` for where this is produced.
 * All three are countable — see `AuxFloatsResult.dropped` — because in every one of them there IS
 * a real `\newlabel` marker, with a real and known label, that the caller is choosing not to
 * report. A marker whose KEY never closed has no such label and is a different outcome again —
 * see `'indeterminate'` below.
 *
 * `'refused'` is a THIRD thing, and deliberately not a `'dropped'` with another reason. A
 * `'dropped'` says "there was a real `\newlabel` entry here and you are not getting it" — a loss
 * the caller suffers. A `'refused'` says the opposite: a `\newlabel`-shaped string was found
 * inside a group whose end could not be verified (see `OpenSpan`), so it is almost certainly not
 * an entry at all but text inside another entry's group, and it was declined rather than
 * believed. Counting the two together would report a fabrication we refused as an entry the
 * caller lost — naming a cause that did not fire, which is the overclaim this file's comments
 * guard against, and the same reason `pdf_geometry` keeps `floatsOmittedBySize` apart from
 * `floatsOmitted` and `floatsDropped`. It carries no label, because nothing about it was parsed:
 * treating its bytes as a label would be the very fabrication being refused.
 *
 * `'indeterminate'` is a FOURTH thing, and it is neither of the other two. It is yielded when a
 * marker's own KEY group was opened (`\newlabel` IS followed by a `{`) but its closing brace was
 * never located: `readGroupOrSkip`'s `'exhausted'` on the key under either reason, or its
 * `'unbalanced'` with `depth >= 1`. The claim it makes is deliberately the weakest of the four —
 * a `\newlabel` marker existed here and we can say NOTHING about it.
 *
 * Not `'dropped'`, which says "there was a real entry and you are not getting it": there is no
 * key text here to know that with, and with no key there is nothing to test `isCleverefShadow`
 * against — so folding it into `dropped` would report a cleveref shadow record (not a float, and
 * excluded from every count in this file) as a lost float. Not `'refused'` either, which says
 * the opposite thing: that nothing is missing, because the bytes were never an entry. Before
 * this outcome existed such a marker produced no outcome at all and vanished with
 * `total`/`dropped`/`refused` all 0 — issue #139 §2, the key-side remainder of #76's FINDING 2.
 * It carries no label for the same reason `'refused'` does not: there is no parsed key to carry,
 * and inventing one from the unterminated bytes is the fabrication this file exists to refuse.
 *
 * The one key-side failure that stays a silent skip is `depth === 0` — `\newlabel` followed by
 * something that is not a `{` at all. Nothing was opened, so there is no evidence a `\newlabel`
 * INVOCATION was ever there (the bytes may be prose, or `\newlabelfoo`), and counting it would
 * put a number on text rather than on a marker. Length is deliberately NOT the line: a key
 * `{` that never closes is `'unbalanced'` when the file ends within `MAX_GROUP_SCAN` of it and
 * `'exhausted'` when it does not, and a counter that fired only past 4096 characters would be
 * drawing a distinction no caller could act on.
 */
/** Shared, mutable scan state — see `scanAuxEntries`. */
interface ScanCursor {
  /** Markers scanned so far, counted against `PARSE_BOUND`. */
  scans: number;
  /** Index in the current file of the marker whose outcome was just yielded. */
  at: number;
}

type ScanOutcome =
  | { kind: 'entry'; entry: AuxLabel }
  | { kind: 'dropped'; label: string; reason: 'fieldTooLong' | 'groupTooLong' | 'keyTooLong' }
  | { kind: 'refused' }
  | { kind: 'indeterminate' };

/**
 * The shared scan behind both `parseAuxLabels` and `readAuxFloats`: walks `aux` for `\newlabel`
 * markers, yielding one outcome per marker that is not a silent skip (see `ScanOutcome` for
 * which failures are which). Bounded on two independent axes (see
 * `MAX_GROUP_SCAN`/`GROUP_SKIP_SCAN`/`PARSE_BOUND` above) so total work
 * is linear in `aux.length` no matter how the file is malformed — none of these bounds depend on
 * how many outcomes the caller actually consumes, so a caller that stops early (`parseAuxLabels`,
 * once it has `maxLabels` entries) does strictly less work, never more.
 *
 * Advances `searchFrom` past a group's end WHENEVER that end is actually known, never on a guess:
 *   - `'ok'`/`'tooLong'` (either the key or the outer group): the marker has consumed that whole
 *     span either way, so re-entering it would let a `\newlabel`-shaped string INSIDE it (e.g. in
 *     hyperref's caption group, or even inside an implausibly long key) be picked up as a second,
 *     fabricated entry — so `searchFrom` always jumps to (at least) the key's own end the moment
 *     the key is located, and to the outer group's end once that is located too.
 *   - `'exhausted'` with `reason: 'tooLong'`: the group's true end is still unknown, but
 *     `readGroupOrSkip` already linearly scanned every character up to `scannedTo`
 *     (`start + GROUP_SKIP_SCAN`) looking for it — so advancing `searchFrom` there is NOT a guess
 *     either, it only skips text this call already read. This closes the fabrication risk for any
 *     `\newlabel`-shaped substring located anywhere within that scanned span, not merely near its
 *     start — before this, not advancing at all left the WHOLE remaining group vulnerable
 *     regardless of where inside it a fake marker sat. Advancing says nothing about the text
 *     BEYOND the budget, though, which is why the same branch also opens an `OpenSpan`: the group
 *     is still open there, and the walk is carried forward marker by marker rather than the group
 *     being declared over (issue #80 §3 — this used to be the residual, and a `\newlabel`-shaped
 *     string more than `GROUP_SKIP_SCAN` characters into the group came back as a real label).
 *   - `'exhausted'` with `reason: 'truncated'`, or plain `'unbalanced'` with `depth >= 1`: the
 *     retry (or the primary attempt) ran off the TRUE end of `aux` without ever finding a closing
 *     brace — there is provably nothing left to find no matter how far we looked, so `searchFrom`
 *     is left wherever it already is (which may still be past the key, if the key itself was
 *     located). Nothing is advanced on these branches; an `OpenSpan` is opened instead, and the
 *     paragraph below is why.
 *
 * While an `OpenSpan` is outstanding, every marker is first resolved AGAINST it: the brace walk
 * is continued from where it stopped to the marker's own index, which either finds the group's
 * close first (the span is over, the marker is ordinary text after it, and it is parsed
 * normally) or does not (the marker is inside the group, and is `'refused'` — never reported,
 * always counted). Here the file continues and the check costs only the characters between two
 * markers, so the fabrication is refusable — and a marker is refused even though the walk may
 * later turn out never to close at all, because the `.aux` is document-controlled and a
 * fabricated label becomes a page `render_pages` renders with confidence, whereas a refused one
 * is a counted gap.
 *
 * There used to be an ASYMMETRY here, and it is gone: a group that closes nowhere in the file
 * was left reportable, so a `\newlabel`-shaped string sitting after it came back as a real entry
 * (issue #80 §3's last sub-case, #139 §1). Two things were wrong with it, in order of
 * importance.
 *
 * The evidence is not absent. On these branches the walk reached the TRUE end of `aux` without
 * the depth ever touching 0, which (see `scanBalance`: a depth reaching 0 returns `'closed'`)
 * PROVES the group is open at every position from `start` to end-of-file. So every later marker
 * is provably inside another entry's argument, and establishing that costs nothing at all — the
 * walk has already been paid for. The comment that once justified the asymmetry with "there is
 * no cheap check left to make" was simply false, and was corrected in #133 before the decision
 * itself was revisited.
 *
 * What actually held it up was a RECALL bet — a corrupt or truncated `.aux` tail probably still
 * holds legitimate records, so keep reporting them — and the repository owner reversed that bet
 * in #139. This module feeds label→page lookup in `render_pages` and `extract_text`, so a
 * fabricated label whose key happens to collide with a requested one resolves to a page the tool
 * then renders WITH CONFIDENCE, off bytes the document itself controls. That is the failure
 * shape the rest of this codebase refuses by construction — `approximate: true` meaning "never
 * use this for a collision computation", a source snippet shown only where its location can be
 * vouched for, `peerEntries` returning `null` for an unreadable index and never "owns nothing",
 * and `refused` itself existing so a declined fake is never miscounted as a missing entry. A
 * counted gap is recoverable; a confident wrong page is not.
 *
 * The recall cost is smaller than it reads, which is part of why the trade flipped. The markers
 * a span now refuses are only those AFTER an unclosed group — and in the shape the bet was made
 * for, an `.aux` cut off mid-write by a killed `latexmk`, the unclosed group IS the last thing
 * in the file, so nothing follows it to refuse. What is given up is recall on a file where a
 * group opens, never closes, and legitimate entries follow it anyway: a file no honest LaTeX run
 * produces. What is bought is that no such file can invent a page number.
 *
 * Every `readGroupOrSkip` call is itself O(1)-bounded regardless of outcome, and the open-span
 * walk reads each character of `aux` at most once across all of its continuations (`next` never
 * moves backwards), so total work stays `O(aux.length) + PARSE_BOUND * (MAX_GROUP_SCAN +
 * GROUP_SKIP_SCAN)` — the same linear bound as before, a pass over `aux` being what `indexOf`
 * already costs. Per marker the span check is amortized O(1) rather than worst-case O(1): a
 * marker far from the previous one pays for the gap, and the markers that gap contains do not
 * exist to pay for it.
 *
 * `cursor`, when given, is shared state for a scan that spans several files (`readAuxFloats`
 * following `\@input`): `scans` is the marker budget, so `PARSE_BOUND` bounds the WHOLE index
 * rather than each file of it, and `at` is set to each marker's index in `aux` before its outcome
 * is yielded, so a lazy consumer can tell where that outcome sits relative to an `\@input` line.
 * Neither changes what the scan yields.
 */
function* scanAuxEntries(
  aux: string,
  work?: ScanWork,
  cursor: ScanCursor = { scans: 0, at: 0 },
): Generator<ScanOutcome> {
  let searchFrom = 0;
  let openSpan: OpenSpan | null = null;
  while (cursor.scans < PARSE_BOUND) {
    const markerIdx = aux.indexOf(NEWLABEL_MARKER, searchFrom);
    if (markerIdx === -1) {
      // The search still read everything left of end-of-file looking for one.
      if (work) work.steps += Math.max(0, aux.length - searchFrom);
      break;
    }
    // `indexOf` looked at every character from `searchFrom` through the end of the match.
    if (work) work.steps += markerIdx + NEWLABEL_MARKER.length - searchFrom;
    cursor.scans++;
    cursor.at = markerIdx;
    // Advance past this marker regardless of what happens below, so a malformed entry cannot
    // wedge the scan in place.
    searchFrom = markerIdx + NEWLABEL_MARKER.length;

    if (openSpan) {
      // Carry the abandoned group's own brace walk forward to this marker — never past it, so
      // the cost is the gap between two markers and each character is walked at most once.
      const walk = scanBalance(aux, openSpan.next, markerIdx, openSpan.depth, work);
      if (walk.kind === 'closed') {
        // The group ended before this marker, so the marker is ordinary text that follows it:
        // the span is over and the marker gets the normal treatment below.
        openSpan = null;
      } else {
        // Still inside the group. This is `\newlabel`-shaped text sitting in another entry's
        // argument, not an entry — refuse it rather than fabricate a label (and a page) from it.
        openSpan = { depth: walk.depth, next: walk.next };
        yield { kind: 'refused' };
        continue;
      }
    }

    let i = skipWs(aux, searchFrom, work);
    const keyGroup = readGroupOrSkip(aux, i, work);
    if (keyGroup.kind === 'unbalanced') {
      if (keyGroup.depth > 0) {
        // A `{` was opened for the key and the walk proved it never closes anywhere in the file.
        // searchFrom is NOT advanced (nothing was located to advance to), but everything after
        // this point is provably inside that group, so carry it as a span and refuse what
        // follows rather than reading it as entries of its own.
        openSpan = { depth: keyGroup.depth, next: keyGroup.next };
        yield { kind: 'indeterminate' };
      }
      // depth 0: `\newlabel` was not followed by a `{` at all. Nothing was opened, so this says
      // nothing about the text after it — no span, and nothing to count. Silent skip, as always.
      continue;
    }
    if (keyGroup.kind === 'exhausted') {
      if (keyGroup.reason === 'tooLong') {
        // Not a guess — scannedTo is exactly how far this call already read; see this function's
        // own doc for why that makes advancing here safe rather than a risk.
        searchFrom = keyGroup.scannedTo;
      }
      // Either reason: the group is still open at `next`, so keep walking it rather than
      // treating whatever follows as text outside it. Under 'tooLong' the file continues and the
      // walk may yet find the close; under 'truncated' it reached end-of-file already and the
      // carried walk is a no-op that can never close, which is the answer wanted.
      openSpan = { depth: keyGroup.depth, next: keyGroup.next };
      // A real \newlabel marker was here and its key never closed, so there is no label to
      // report and nothing to test for a cleveref shadow. Counted as its own outcome rather than
      // vanishing (#139 §2) — see ScanOutcome for why it is neither a drop nor a refusal.
      yield { kind: 'indeterminate' };
      continue;
    }

    // keyGroup is 'ok' or 'tooLong' — either way its end is real and known, so it is always safe
    // to resume from there even if everything that follows (the outer group) turns out malformed.
    const keyTooLong = keyGroup.kind === 'tooLong';
    const keyContent = keyGroup.content;
    searchFrom = keyGroup.end;

    i = skipWs(aux, keyGroup.end, work);
    const outerGroup = readGroupOrSkip(aux, i, work);
    if (outerGroup.kind === 'unbalanced') {
      // Truly no closing brace anywhere in the rest of the file for this group. searchFrom stays
      // at the key's own (already-known-safe) end from above; nothing further is located. But
      // when a `{` WAS opened (depth >= 1), the walk has proven it stays open to end-of-file, so
      // every later marker is inside it: carry the span. depth 0 means there was no group here
      // at all (nothing followed the key), which is evidence about nothing.
      if (outerGroup.depth > 0) {
        openSpan = { depth: outerGroup.depth, next: outerGroup.next };
      }
      continue;
    }
    if (outerGroup.kind === 'exhausted') {
      if (outerGroup.reason === 'tooLong') {
        searchFrom = outerGroup.scannedTo;
      }
      // Either reason opens the span, for the reason the key's own branch above records: under
      // 'truncated' searchFrom stays at keyGroup.end and the group is proven open from here to
      // end-of-file, so what follows is another entry's argument, not entries.
      openSpan = { depth: outerGroup.depth, next: outerGroup.next };
      // The key DID parse — there is a real label here — so this is no longer a silent skip: the
      // caller gets a countable 'dropped' outcome instead of the entry simply vanishing.
      yield {
        kind: 'dropped',
        label: keyContent,
        reason: keyTooLong ? 'keyTooLong' : 'groupTooLong',
      };
      continue;
    }
    if (outerGroup.kind === 'tooLong') {
      // A well-formed \newlabel whose outer group is longer than MAX_GROUP_SCAN accepts. We
      // found its TRUE end via the GROUP_SKIP_SCAN retry, so jump cleanly past the whole group —
      // including anything \newlabel-shaped inside it — instead of resuming partway through it.
      searchFrom = outerGroup.end;
      yield {
        kind: 'dropped',
        label: keyContent,
        reason: keyTooLong ? 'keyTooLong' : 'groupTooLong',
      };
      continue;
    }
    // outerGroup.kind === 'ok'. The whole outer group has been consumed either way (success or a
    // downstream field-shape failure below) — jump past it so nothing inside it is ever
    // re-entered as its own marker.
    searchFrom = outerGroup.end;

    if (keyTooLong) {
      // Both groups are now fully located and consumed cleanly, but the key itself was never a
      // usable label (see the ScanOutcome doc for what `keyContent` holds and why it is still
      // worth reporting).
      yield { kind: 'dropped', label: keyContent, reason: 'keyTooLong' };
      continue;
    }

    // The outer group's content starts with two brace groups: {number}{page}[...]. Read them with
    // the same balanced reader, ignoring anything after (hyperref appends {\relax }{anchor}{}).
    // This content is already bounded to at most MAX_GROUP_SCAN characters (outerGroup succeeded
    // under that budget to get here), so these two reads can never themselves hit a scan budget —
    // only genuine unbalance is possible, and that stays a silent skip as it always has.
    const inner = outerGroup.content;
    let j = skipWs(inner, 0, work);
    const numberGroup = readBraceGroup(inner, j, MAX_GROUP_SCAN, work);
    if (numberGroup.kind !== 'ok') {
      continue;
    }
    j = skipWs(inner, numberGroup.end, work);
    const pageGroup = readBraceGroup(inner, j, MAX_GROUP_SCAN, work);
    if (pageGroup.kind !== 'ok') {
      continue;
    }

    const label = keyContent;
    const number = numberGroup.content;
    const page = pageGroup.content;
    if (
      label.length > MAX_FIELD_LENGTH ||
      number.length > MAX_FIELD_LENGTH ||
      page.length > MAX_FIELD_LENGTH
    ) {
      yield { kind: 'dropped', label, reason: 'fieldTooLong' };
      continue;
    }

    yield { kind: 'entry', entry: { label, number, page } };
  }
}

function collectAuxLabels(aux: string, maxLabels: number, work?: ScanWork): AuxLabel[] {
  const results: AuxLabel[] = [];

  for (const outcome of scanAuxEntries(aux, work)) {
    if (outcome.kind !== 'entry') {
      continue;
    }
    results.push(outcome.entry);
    if (results.length >= maxLabels) {
      break;
    }
  }

  return results;
}

export function parseAuxLabels(aux: string, opts?: { maxLabels?: number }): AuxLabel[] {
  return collectAuxLabels(aux, opts?.maxLabels ?? DEFAULT_MAX_LABELS);
}

/**
 * `parseAuxLabels`, plus the number of characters the scan looked at getting there — the test
 * seam for this module's linearity guarantee (see `ScanWork`). It is a SEPARATE export rather
 * than an option on `parseAuxLabels` so that nothing a production caller can pass turns
 * instrumentation on: `parseAuxLabels` and `readAuxFloats` call the scan with no accumulator at
 * all, and their behaviour and return types are untouched by this existing. It runs the same
 * `collectAuxLabels` over the same generator with the same early stop, so what it counts is the
 * work the real parse does — not a re-implementation of it, which is the one way a work counter
 * can go quietly wrong. `labels` is returned alongside `steps` so a test can assert the parse's
 * OUTCOME in the same call it measures; a measurement of a scan that stopped early for the wrong
 * reason would otherwise look like excellent linearity.
 */
export function measureAuxScanWork(
  aux: string,
  opts?: { maxLabels?: number },
): { labels: AuxLabel[]; steps: number } {
  const work: ScanWork = { steps: 0 };
  const labels = collectAuxLabels(aux, opts?.maxLabels ?? DEFAULT_MAX_LABELS, work);
  return { labels, steps: work.steps };
}

/** `pdf_geometry`'s "floats" cap — labels past this are reported as `omitted`, never silently. */
export const DEFAULT_MAX_FLOATS = 200;

/**
 * cleveref's internal shadow records: for every `\label{x}` it also writes `\newlabel{x@cref}`
 * whose "number"/"page" fields are its own bracketed cross-reference codes (e.g.
 * `[figure][1][]1` / `[1][1][]1`), not printed page numbers at all. Verified against a real
 * `pdflatex` + cleveref run (this repo's own tex install, cleveref's `\newlabel` macros in
 * cleveref.sty around `\cref@constructprefix`/`\@newl@bel`): the only shadow suffix cleveref
 * emits is `@cref` — no separate `@cref@...` sibling was found. `parseAuxLabels` itself stays
 * faithful to the file and returns these; filtering them out of the "floats" index happens here,
 * one layer up, so a caller of the pure parser still sees exactly what the `.aux` says.
 */
const CLEVEREF_SHADOW_SUFFIXES = ['@cref'];

function isCleverefShadow(label: string): boolean {
  return CLEVEREF_SHADOW_SUFFIXES.some((suffix) => label.endsWith(suffix));
}

export interface AuxFloatsResult {
  /** Real (non-shadow) labels, capped at `opts.max` (default DEFAULT_MAX_FLOATS), in the order
   *  LaTeX reads them — the root's records with each `\@input`-ed file's spliced in where the
   *  root inputs it (see `scanWithInputs`). Because `\label` writes at shipout, that order is
   *  page order; `labelPages.ts` relies on it to see an arabic numbering restart. */
  floats: AuxLabel[];
  /** Real labels found past the `max` cap — `total - floats.length`. Exact (computed against the
   *  TRUE total in `total`, not a smaller parse-time cutoff) as long as the file contains at most
   *  `PARSE_BOUND` `\newlabel` markers; see `total`'s doc for what happens past that. */
  omitted: number;
  /** The true count of real (non-shadow), successfully-parsed labels found in the file — i.e.
   *  `floats.length + omitted`, before the `max` cap is applied. A label counted here always has
   *  a valid `AuxLabel` behind it; one dropped for an over-length field or an over-budget group
   *  (see `dropped` below) is deliberately excluded, the same way it always has been for the
   *  former. Exact for any file (the root `.aux` and every file it `\@input`s, which share one
   *  budget) with at most `PARSE_BOUND` `\newlabel` markers (shadow entries
   *  included in that count, since every marker costs a scan regardless of what it turns out to
   *  be) — a document with more markers than that is far past anything real, and both `total` and
   *  `omitted` saturate at whatever `PARSE_BOUND` allowed rather than reflecting the file's actual
   *  count. */
  total: number;
  /** Real (non-shadow) `\newlabel` entries found but dropped because there was no valid
   *  `AuxLabel` to report for them — never included in `total` or `floats` either way, counted
   *  here instead so the drop is never silent. Three distinct causes land in this one count (see
   *  `ScanOutcome`'s doc for the exact mechanics of each): a field (label, number, or page)
   *  exceeded the per-field length cap (`MAX_FIELD_LENGTH`) after the entry otherwise parsed
   *  cleanly; the entry's outer group (holding number/page/caption) exceeded the `MAX_GROUP_SCAN`
   *  scan budget before a matching `}` was found, whether or not its true end was ever located;
   *  or the KEY itself exceeded `MAX_GROUP_SCAN` before a matching `}` was found for IT. All three
   *  are, from a caller's point of view, the same fact: "there was a real `\newlabel` marker here
   *  we could not give you a usable entry for." */
  dropped: number;
  /** `\newlabel`-shaped strings found INSIDE a group whose closing brace neither scan budget
   *  could locate (see `OpenSpan`), refused rather than reported. Deliberately its own count and
   *  never folded into `dropped`: `dropped` means "a real entry you are not getting", while this
   *  means the opposite — text inside another entry's argument that we declined to believe was
   *  an entry at all. Reporting a refused fabrication as a dropped entry would name a cause that
   *  did not fire. Almost always 0; a non-zero value means the `.aux` is malformed or hostile,
   *  not that the index is incomplete. Optional only so that object literals of this type
   *  written elsewhere keep compiling — `readAuxFloats` always sets it. */
  refused?: number;
  /** `\newlabel` markers whose own KEY group was opened but whose closing brace neither scan
   *  budget could locate, so nothing at all about them could be read (see `ScanOutcome`'s
   *  `'indeterminate'`). Its own count, added to NONE of the others and never folded into them:
   *  `dropped` means "a real entry is missing", `refused` means "nothing is missing, a fake was
   *  declined", and this means neither — a marker existed and we can say nothing about it. There
   *  is no key text here, so it cannot even be tested for a cleveref shadow, which is why
   *  counting it as `dropped` would be wrong rather than merely imprecise. Before #139 these
   *  markers vanished with every counter at zero. Almost always 0; a non-zero value means the
   *  `.aux` is malformed or hostile. Optional for the same reason `refused` is — `readAuxFloats`
   *  always sets it. */
  indeterminate?: number;
  /** How many `\@input`-ed `.aux` files (which `\include` writes, one per chapter) were named
   *  but not read — not in the build directory, too large, past the file or depth cap — so the
   *  index may be missing those chapters' labels. `note` names them; this is the count a caller
   *  decides on, so no caller has to match the note's wording. Optional for the same reason
   *  `refused` is — `readAuxFloats` always sets it. Never spread into a tool's
   *  `structuredContent` (no tool spreads this result), so it needs no `outputSchema` entry. */
  unreadInputs?: number;
  /** Whether any `.aux` read carries beamer's navigation records (`\@writefile{nav}` lines,
   *  see {@link isBeamerAux}) — the document is a beamer deck, whose `/PageLabels` number FRAMES
   *  while every `\newlabel` records the SLIDE, so `labelPages.ts` must not look a printed page
   *  up in that tree. Optional for the same reason `refused` is — `readAuxFloats` always sets it.
   *  Never spread into a tool's `structuredContent`. */
  beamerNav?: boolean;
  /** beamer's own record of the slide each `\label` ran on (`\beamer@slide`, see
   *  {@link BEAMER_SLIDE_LINE}): label -> the distinct slides recorded for it, in `.aux` order, at
   *  most {@link MAX_SLIDES_PER_LABEL}. `labelPages.ts` refuses a deck's label whose `\newlabel`
   *  printed page is not among them — the mark of a `pgfpages` layout that shifted every label.
   *  Present only when some file read carries at least one record. Never spread into a tool's
   *  `structuredContent`. */
  beamerSlides?: ReadonlyMap<string, readonly string[]>;
  /** Whether the build that wrote this `.aux` loaded `pgfpages` ({@link readPgfpagesEvidence}):
   *  `true` when its recorder file (`.fls`) or its `.log` names `pgfpages.sty`, `false` when at
   *  least one of the two was read and neither does, and absent when neither could be read (no
   *  `.aux` at all, or a backend that wrote neither). `labelPages.ts` refuses every label of a
   *  `true` build (`'pgfpagesLayout'`): a pgfpages layout shifts every `\newlabel` a page late.
   *  It refuses every label when this is absent too (`'pgfpagesUnknown'`), since the shift is
   *  invisible everywhere else, and `pdf_geometry` then notes that its floats pages are
   *  unverified; only `false` lets a label resolve. Never spread into a tool's
   *  `structuredContent`. */
  pgfpages?: boolean;
  /** The page counter (`\count0`) each PDF page was shipped out with, in page order, read off the
   *  shipout marks of the build's `.log` ({@link readShipoutMarks}). Present only when the
   *  caller asked for it (`readAuxFloats(…, { shipouts: true })`) and the log was read and parsed
   *  whole; absent otherwise — never a partial list. `labelPages.ts` uses it only to REFUSE a
   *  label whose resolved page was shipped under another counter, and only when its length is
   *  the PDF's page count. Never spread into a tool's `structuredContent`. */
  shipouts?: readonly number[];
  /** Present when no `.aux` was found in the build directory, or when the root `.aux` inputs
   *  (`\@input`, which `\include` writes) a file that could not be read — so the index may be
   *  missing that chapter's labels. Absent otherwise. */
  note?: string;
}

/**
 * How many `\@input`-ed `.aux` files one `readAuxFloats` call reads, beyond the root. A book of
 * `\include`d chapters has one per chapter — dozens, not hundreds — so this is far above anything
 * real while keeping the bytes read bounded: each file is also capped at `MAX_READ_BYTES`, the
 * same per-file cap `read_file` applies, and the markers of every file together share one
 * `PARSE_BOUND`.
 */
export const MAX_AUX_INPUTS = 256;
/** How deep `\@input`s nest. `\include` cannot nest, so a real document needs exactly 1. */
export const MAX_AUX_INPUT_DEPTH = 8;
/** How many path components an `\@input` name may have (see `findBuildDirAux`). A real
 *  `\include{chapters/one}` has two. */
const MAX_INPUT_PATH_DEPTH = 16;
/** How many unread inputs a note names before it summarises the rest as a count. */
const MAX_NOTED_INPUTS = 5;

/**
 * An `\@input{…}` at the start of a line — the shape `\include` writes into the root `.aux`
 * (`\immediate\write\@mainaux{\string\@input{chap.aux}}`, always on its own line). Line-
 * anchored so that the same text sitting inside a `\newlabel`'s caption group, which LaTeX
 * stores but never executes, is not taken for an input.
 */
const AUX_INPUT_LINE = /^[ \t]*\\@input\{([^{}\r\n]*)\}/gm;

/**
 * A `\@writefile{nav}{...}` at the start of a line: beamer writes one per slide and frame into
 * the `.aux` (to build its `.nav` file), and no other class writes to a `nav` stream. Line-
 * anchored like {@link AUX_INPUT_LINE}, so the text inside a caption group is not taken for one
 * — and a forged one only moves label resolution onto its stricter, folio-checked route.
 */
const BEAMER_NAV_LINE = /^[ \t]*\\@writefile\{nav\}/m;

/** Whether one `.aux` file's content is a beamer deck's (see {@link BEAMER_NAV_LINE}). */
export function isBeamerAux(content: string): boolean {
  return BEAMER_NAV_LINE.test(content);
}

/**
 * beamer's own record of the slide a `\label` ran on, `\@writefile{snm}{\beamer@slide {<label>}{<slide>}}`
 * at the start of a line — written by `\beamer@nameslide`, which every `\label` in a deck calls
 * beside LaTeX's own. The two records are written at different MOMENTS: `\newlabel` expands
 * `\thepage` when the page SHIPS, while beamer's `\addtocontents` expands `\the\c@page` when the
 * `\label` runs. They agree unless something moves the shipout — a `pgfpages` layout holds each
 * page back until the next one is built, so every `\newlabel` records the page after its own
 * while this record keeps the true slide. Line-anchored like {@link AUX_INPUT_LINE}, so the text
 * inside a caption group is not taken for one. A forged record can only ADD a refusal — the check
 * refuses when any record disagrees and never accepts on one — so line anchoring is enough here.
 *
 * Each field is read by {@link SLIDE_FIELD}: one level of balanced braces, and a backslash escaping
 * the character after it — the rules `readBraceGroup` applies to a `\newlabel` key, as far as one
 * level goes — so `\label{fig:{a}}` is recorded under `fig:{a}`, the key its `\newlabel` is
 * stored under, and the check applies to it. A key nested deeper than that yields no record, and
 * its label then keeps the folio route, as a label with no record always has (`lastpage`'s
 * `LastPage`): nothing contradicts it, so that is not a pass on less evidence than before.
 */
const SLIDE_FIELD = String.raw`\{((?:\\.|[^{}\\\r\n]|\{(?:\\.|[^{}\\\r\n])*\})*)\}`;
const BEAMER_SLIDE_LINE = new RegExp(
  String.raw`^[ \t]*\\@writefile\{snm\}\{\\beamer@slide[ \t]*` +
    SLIDE_FIELD +
    SLIDE_FIELD +
    String.raw`\}`,
  'gm',
);

/**
 * How many distinct slides are kept per label. Two already decide the check (at most one of them
 * can equal the printed page); the rest are headroom for the refusal to name, and the cap keeps a
 * hostile `.aux` repeating one label from growing an unbounded list.
 */
export const MAX_SLIDES_PER_LABEL = 8;

/** Add one file's `\beamer@slide` records to `into` (see {@link BEAMER_SLIDE_LINE}). */
function collectBeamerSlides(content: string, into: Map<string, string[]>): void {
  for (const m of content.matchAll(BEAMER_SLIDE_LINE)) {
    const label = m[1] ?? '';
    const slide = m[2] ?? '';
    // Past the cap no \newlabel field is ever reported (MAX_FIELD_LENGTH), so such a label has
    // no entry to check; an over-long slide is cut but stays unequal to any reportable page.
    if (label.length > MAX_FIELD_LENGTH) continue;
    const kept = slide.length > MAX_FIELD_LENGTH ? `${slide.slice(0, MAX_FIELD_LENGTH)}…` : slide;
    const slides = into.get(label);
    if (!slides) {
      into.set(label, [kept]);
    } else if (!slides.includes(kept) && slides.length < MAX_SLIDES_PER_LABEL) {
      slides.push(kept);
    }
  }
}

type UnreadReason = 'notInBuildDir' | 'caseMismatch' | 'tooLarge' | 'tooMany' | 'tooDeep';

interface AuxInputWalk {
  outcomes: ScanOutcome[];
  /** Whether any file walked is a beamer deck's `.aux` ({@link isBeamerAux}). */
  beamerNav: boolean;
  /** Every walked file's `\beamer@slide` records ({@link collectBeamerSlides}). */
  beamerSlides: Map<string, string[]>;
  /** `found` is the build dir's own spelling of the component a `caseMismatch` stopped at. */
  unread: { name: string; reason: UnreadReason; found?: string }[];
}

/** Where an `\@input` led: the file to read, or why there is none (see `findBuildDirAux`). */
type BuildDirAuxLookup =
  | { abs: string }
  | { miss: 'notInBuildDir' }
  | { miss: 'caseMismatch'; found: string };

/**
 * Find the `.aux` an `\@input` names, under the build dir, WITHOUT using the name as a path.
 * The name (already POSIX-normalized) is split into components and each is looked up in a
 * listing of the directory reached so far — an exact, literal match against a `readdir` entry —
 * so `..`, an absolute name, an empty component, or anything the filesystem would interpret
 * (a case fold, a trailing dot, a stream suffix) simply finds nothing. Every intermediate
 * component must be a real directory and the last a regular file ending in `.aux`: symbolic
 * links are neither followed into (a linked directory is not a directory to `Dirent`) nor read
 * (a linked file is not a file to it).
 *
 * Looked up along the name's own path, rather than by enumerating the whole build dir, because
 * that is all the question needs, and because the whole build dir is not the compiler's alone:
 * `render_pages` writes one `render/page-<n>-<hash>.png` per distinct request and nothing
 * prunes them. An enumeration under an entry budget let enough renders use the budget up before
 * a chapter's subdirectory was reached. `listings` caches each directory's entries for the call,
 * so a book of chapters in one subdirectory lists it once.
 *
 * A miss is diagnosed, never repaired: when the component that missed matches exactly ONE entry
 * of the right kind case-insensitively, the result says so (`caseMismatch`, with the build dir's
 * spelling). On Windows and macOS LaTeX itself opens `chapters/one.aux` in a `Chapters/` the build
 * dir kept from an earlier compile (or mirrored from the source tree), so the generic "not
 * compiled yet" advice sent the caller to recompile the whole document, which leaves every
 * spelling as it is and so never helps. The entry is
 * still not read — matching it would be the case fold this lookup refuses to perform, and with
 * two candidates there is no telling which one LaTeX read.
 */
async function findBuildDirAux(
  build: string,
  key: string,
  listings: Map<string, Dirent[] | null>,
): Promise<BuildDirAuxLookup> {
  const notFound = { miss: 'notInBuildDir' } as const;
  const parts = key.split('/');
  if (parts.length > MAX_INPUT_PATH_DEPTH) return notFound;
  let abs = build;
  for (const [i, part] of parts.entries()) {
    if (part === '' || part === '.' || part === '..') return notFound;
    let entries = listings.get(abs);
    if (entries === undefined) {
      try {
        entries = await readdir(abs, { withFileTypes: true });
      } catch (err) {
        const code = (err as NodeJS.ErrnoException).code;
        if (code !== 'ENOENT' && code !== 'ENOTDIR') throw err;
        entries = null;
      }
      listings.set(abs, entries);
    }
    const last = i === parts.length - 1;
    const fits = (e: Dirent) => (last ? e.isFile() && e.name.endsWith('.aux') : e.isDirectory());
    const entry = entries?.find((e) => e.name === part);
    if (!entry) {
      const folded = part.toLowerCase();
      const near = (entries ?? []).filter((e) => e.name.toLowerCase() === folded && fits(e));
      return near.length === 1 ? { miss: 'caseMismatch', found: near[0]!.name } : notFound;
    }
    if (!fits(entry)) return notFound;
    abs = path.join(abs, part);
  }
  return { abs };
}

/**
 * Read one listed `.aux`, re-checking at read time what the listing established: still a regular
 * file (not swapped for a link since), its real path still inside the build dir's, and no larger
 * than `MAX_READ_BYTES`. A file that vanished in between is reported as not in the build dir.
 */
async function readListedAux(
  abs: string,
  buildReal: string,
): Promise<string | 'notInBuildDir' | 'tooLarge'> {
  try {
    const st = await lstat(abs);
    if (!st.isFile()) return 'notInBuildDir';
    const rel = path.relative(buildReal, await realpath(abs));
    if (rel === '' || rel.startsWith('..') || path.isAbsolute(rel)) return 'notInBuildDir';
    if (st.size > MAX_READ_BYTES) return 'tooLarge';
    return await readFile(abs, 'utf8');
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return 'notInBuildDir';
    throw err;
  }
}

/**
 * The scan outcomes of the root `.aux` and every file it `\@input`s, in the order LaTeX reads
 * them: the root's own entries up to an `\@input` line, then that file's (recursively), then the
 * root's again. The order is what LaTeX's own is because a label defined twice ends up with its
 * LAST definition, so a consumer that has to pick one needs the sequence LaTeX saw. Each file is
 * read at most once — a repeat or a cycle adds nothing a first read did not — and the build dir
 * is listed only when an `\@input` is actually present, so an ordinary document pays nothing.
 */
async function scanWithInputs(
  rootContent: string,
  rootKey: string,
  build: string,
): Promise<AuxInputWalk> {
  const cursor: ScanCursor = { scans: 0, at: 0 };
  const outcomes: ScanOutcome[] = [];
  const unread: AuxInputWalk['unread'] = [];
  const seen = new Set<string>([rootKey]);
  const listings = new Map<string, Dirent[] | null>();
  let buildReal: string | undefined;
  let filesRead = 0;
  let beamerNav = false;
  const beamerSlides = new Map<string, string[]>();

  async function follow(name: string, depth: number): Promise<void> {
    const key = path.posix.normalize(name.trim());
    if (seen.has(key)) return;
    seen.add(key);
    if (depth >= MAX_AUX_INPUT_DEPTH) {
      unread.push({ name, reason: 'tooDeep' });
      return;
    }
    if (filesRead >= MAX_AUX_INPUTS) {
      unread.push({ name, reason: 'tooMany' });
      return;
    }
    const found = await findBuildDirAux(build, key, listings);
    if ('miss' in found) {
      unread.push(
        found.miss === 'caseMismatch'
          ? { name, reason: 'caseMismatch', found: found.found }
          : { name, reason: 'notInBuildDir' },
      );
      return;
    }
    const abs = found.abs;
    buildReal ??= await realpath(build);
    const content = await readListedAux(abs, buildReal);
    if (content === 'notInBuildDir' || content === 'tooLarge') {
      unread.push({ name, reason: content });
      return;
    }
    filesRead++;
    await walk(content, depth + 1);
  }

  async function walk(content: string, depth: number): Promise<void> {
    beamerNav ||= isBeamerAux(content);
    collectBeamerSlides(content, beamerSlides);
    const inputs = [...content.matchAll(AUX_INPUT_LINE)].map((m) => ({
      at: m.index,
      name: m[1] ?? '',
    }));
    let next = 0;
    // Lazily, so each outcome's position (`cursor.at`, set just before it is yielded) can be
    // compared with the inputs' before it is placed. A nested walk moves the shared cursor, which
    // is why `at` is read at once.
    for (const outcome of scanAuxEntries(content, undefined, cursor)) {
      const at = cursor.at;
      while (next < inputs.length && inputs[next]!.at < at) {
        await follow(inputs[next++]!.name, depth);
      }
      outcomes.push(outcome);
    }
    while (next < inputs.length) await follow(inputs[next++]!.name, depth);
  }

  await walk(rootContent, 0);
  return { outcomes, beamerNav, beamerSlides, unread };
}

/** The note for inputs that were not read — each named (bounded), with why, and what to do. */
function unreadInputsNote(walk: AuxInputWalk): string | undefined {
  if (walk.unread.length === 0) return undefined;
  const why: Record<UnreadReason, string> = {
    notInBuildDir: 'not found in the build directory',
    caseMismatch: 'spelled differently in the build directory',
    tooLarge: `larger than the ${MAX_READ_BYTES}-byte cap`,
    tooMany: `past the ${MAX_AUX_INPUTS}-file cap`,
    tooDeep: `nested more than ${MAX_AUX_INPUT_DEPTH} \\@input levels deep`,
  };
  const bounded = (s: string) =>
    JSON.stringify(s.length > MAX_FIELD_LENGTH ? `${s.slice(0, MAX_FIELD_LENGTH)}…` : s);
  const named = walk.unread.slice(0, MAX_NOTED_INPUTS).map(({ name, reason, found }) => {
    const holds = found === undefined ? '' : `, which holds ${bounded(found)}`;
    return `${bounded(name)} (${why[reason]}${holds})`;
  });
  const more = walk.unread.length - named.length;
  const parts = [
    `The .aux lists ${walk.unread.length} \\@input file(s) that were not read, so any labels ` +
      `they define are missing from this index: ${named.join(', ')}` +
      (more > 0 ? `, and ${more} more.` : '.'),
  ];
  if (walk.unread.some((u) => u.reason === 'notInBuildDir')) {
    parts.push(
      "\\include writes each chapter's labels to its own .aux, so one missing from the build " +
        'directory is a chapter this build directory has not compiled yet — compile the whole ' +
        'document (with no \\includeonly leaving that chapter out) and retry. Only .aux files ' +
        'inside the build directory are ever read, and never through a symbolic link.',
    );
  }
  if (walk.unread.some((u) => u.reason === 'caseMismatch')) {
    parts.push(
      'A name that differs from a build-directory entry only in letter case is not read (on ' +
        'Windows and macOS LaTeX opens it regardless). Where the differing part is a directory, ' +
        "the build directory mirrors the project's own directory names, so spell the \\include " +
        'the way the project spells that directory. Where it is the .aux file itself, the file ' +
        'keeps the spelling of the compile that first wrote it: spell the \\include the way the ' +
        'file is named, or compile with clean: true (latexmk deletes the files it generated, so ' +
        'the next compile writes it anew under the current spelling).',
    );
  }
  return parts.join(' ');
}

/**
 * A recorder-file (`.fls`) line naming `pgfpages.sty` — or `pgfmorepages.sty`, its drop-in
 * extension, which defines the same `\pgfpagesuselayout` and page-holding shipout without loading
 * `pgfpages.sty` — as a file the engine opened, under any directory and either separator
 * (`INPUT ./pgfpages.sty`, `INPUT C:\…\pgfpages.sty`). Anchored to the whole line, so neither
 * `mypgfpages.sty` nor `pgfpages.sty.bak` is taken for it. The engine writes these lines itself
 * (`-recorder`, which latexmk always passes), so the document cannot write one without opening
 * the file.
 */
const FLS_PGFPAGES = /^INPUT (?:.*[\\/])?pgf(?:more)?pages\.sty\r?$/m;

/**
 * The marks `pgfpages.sty` (or `pgfmorepages.sty`, see {@link FLS_PGFPAGES}) leaves in a `.log`:
 * TeX's file-open `(…/pgfpages.sty`, the `Package: pgfpages <date>` line its `\ProvidesPackage`
 * writes, and the `\pgfpages@shipoutbox=\box<n>` register both packages allocate. More than one,
 * because TeX wraps a log line at 79 characters and a long path can be cut inside the file name,
 * while the other two are short and always start a line. Bounded on both sides like
 * {@link FLS_PGFPAGES}, so another package whose name merely contains `pgfpages` (`mypgfpages`,
 * `pgfpagesx`) is not taken for it.
 *
 * The log is document-controlled — `\typeout{(pgfpages.sty}` forges either mark — and that is
 * acceptable here only because of what the answer is used for: `true` REFUSES every label
 * (`labelPages.ts`), so a forged mark can only add a refusal, never resolve a page. What a
 * document cannot do from inside the log is remove the marks the real package writes.
 */
const LOG_PGFPAGES =
  /(?:^|[\s(/\\])pgf(?:more)?pages\.sty(?=[\s)]|$)|^Package: pgf(?:more)?pages\s|^\\pgfpages@shipoutbox=\\box/m;

/**
 * Up to `MAX_READ_BYTES` from the start of a build-dir file, as text, or `undefined` when there is
 * no such regular file. Opened without following a symbolic link (where the platform can say so)
 * and checked to be a regular file on the open handle. Only the start is read: `pgfpages` is a
 * preamble package, so both of its marks sit near the top of either file, and a build large
 * enough to reach the cap is not read in full for a question the preamble answers.
 */
async function readBuildFileHead(file: string): Promise<string | undefined> {
  let handle;
  try {
    handle = await open(file, fsConstants.O_RDONLY | (fsConstants.O_NOFOLLOW ?? 0));
  } catch (err) {
    const code = (err as NodeJS.ErrnoException).code;
    if (code === 'ENOENT' || code === 'ELOOP' || code === 'ENOTDIR' || code === 'EISDIR') {
      return undefined;
    }
    throw err;
  }
  try {
    const st = await handle.stat();
    if (!st.isFile()) return undefined;
    const length = Math.min(st.size, MAX_READ_BYTES);
    const buf = Buffer.alloc(length);
    const { bytesRead } = await handle.read(buf, 0, length, 0);
    return buf.subarray(0, bytesRead).toString('utf8');
  } finally {
    await handle.close();
  }
}

/**
 * Whether the build that wrote `auxPath` loaded `pgfpages` — which `labelPages.ts` must know,
 * because every `\pgfpagesuselayout` (`resize to`, `2 on 1`, …) holds each page back until the
 * next one is built, so every `\newlabel` records a page later than its own, in any document
 * class, and hyperref's `/PageLabels` tree and the printed folios move with it: neither label
 * route can see the shift. The `.aux` itself says nothing about packages, so the evidence is the
 * build's other two records of what it read, beside the `.aux` under the same job name:
 *
 *  - the recorder file (`.fls`), which latexmk always asks for — the primary source, written by
 *    the engine rather than the document;
 *  - the `.log` ({@link LOG_PGFPAGES}), read as well rather than only when there is no `.fls`: a
 *    `.fls` left by an earlier compile (a project `latexmkrc` that turned the recorder off since)
 *    is stale, while the engine rewrites the `.log` on every run. Tectonic writes a `.log`
 *    (`--keep-logs`) and no `.fls`; it keeps no `.aux` either, so no label resolves there anyway.
 *
 * Either one naming `pgfpages.sty` (or `pgfmorepages.sty`) is `true`: the answer only ever
 * refuses, so the union is the safe reading. `false` needs at least one of the two read and
 * neither naming it. `undefined` — neither readable — means nothing is known, and that is not a
 * pass: `labelPages.ts` refuses every label of such a build (`'pgfpagesUnknown'`) and
 * `pdf_geometry` notes that its floats pages are unverified. Every compile leaves a `.log`, so
 * this state means the records were removed or unreadable, and failing closed costs a recompile.
 * Loading the package without calling `\pgfpagesuselayout` does not shift anything, and is still
 * `true`: the build's records show the package, not the layout, and over-refusing is the
 * direction to err in. The same holds for a file merely opened — the `.fls` records one that
 * `\IfFileExists{pgfpages.sty}` only tested for — which is likewise `true`.
 */
export async function readPgfpagesEvidence(auxPath: string): Promise<boolean | undefined> {
  const stem = auxPath.slice(0, -path.extname(auxPath).length);
  const fls = await readBuildFileHead(`${stem}.fls`);
  if (fls !== undefined && FLS_PGFPAGES.test(fls)) return true;
  const log = await readBuildFileHead(`${stem}.log`);
  if (log !== undefined && LOG_PGFPAGES.test(log)) return true;
  return fls === undefined && log === undefined ? undefined : false;
}

/**
 * The largest `.log` read for its shipout marks. Unlike the pgfpages evidence (a preamble
 * question, answered by the head of the file), the marks run through the whole log, so it is read
 * whole or not at all: a log past this cap yields no marks rather than the marks of its first
 * part. 8 MiB is far past any real log — a 130-page document writes under 4 KB of marks.
 */
export const MAX_SHIPOUT_LOG_BYTES = 8 * 1024 * 1024;

/**
 * One shipout mark: `[`, `\count0`, then `.`-separated `\count1`..`\count9` up to the last
 * nonzero one, followed by `]` (a page shipped with nothing more to say), `{` (the font map file
 * pdfTeX loads with the first page), `<` (an image or font file written into it; LuaTeX puts no
 * space before it), whitespace or the end of the line. TeX puts a space before the `[` whenever
 * the line already holds something, and starts a new line instead when the terminal line is
 * nearly full, so a mark is only ever at the start of a line or after whitespace. Bounded: ten
 * digits hold any `\count` value, and there are nine further counters at most.
 */
const SHIPOUT_MARK = /(?<!\S)\[(-?\d{1,10})(?:\.-?\d{1,10}){0,9}(?=[\]{<\s]|$)/g;

/** The first line of a box warning, whose display (the lines up to the next empty one) quotes the
 *  document. `Tight`/`Loose` are what TeX writes when `\hbadness`/`\vbadness` is set low. */
const BOX_WARNING = /^(?:Overfull|Underfull|Tight|Loose) \\[hv]box \(/;

/** A box warning raised while the output routine was active: its display (` []`) is on the
 *  warning's own line, so the block is that one line. */
const OUTPUT_ACTIVE_BOX_WARNING = /has occurred while \\output is active/;

/**
 * The first line of a TeX error: `<file>:<line>: ` under `-file-line-error` (which the server
 * always passes), `! ` otherwise. TeX follows it with the error's context, its help text and an
 * empty line (`error`), all before anything else is written — so the block through that empty
 * line holds no mark, only document text the context and a document's `\errhelp` quote.
 */
const ERROR_START = /^(?:! |(?:\.\/)?[^:\s][^:]*\.\w+:\d+: )/;

/**
 * The first line of a context pair outside an error — a pdfTeX warning shows the context too
 * (`destination with the same identifier … has been already used`) — which quotes the source up
 * to where TeX stopped: `l.<n> ` for a line of a file, or one of TeX's token-list descriptors
 * (`<*>`, `<argument>`, `<inserted text>`, `<to be read again>`, `<read 0>`, …). Lower-case
 * letters and spaces only, so an image or font path (`</usr/…/cmr10.pfb>`) is not one. Only
 * this line is skipped: nothing ends the pair's second line, and the page shipped next writes its
 * mark onto it (`                   [1`, a real pdflatex + hyperref log).
 */
const ERROR_CONTEXT = /^(?:l\.\d+ |<(?:\*|read \*|read \d+|[a-z][a-z ]{0,20})> )/;

/**
 * The page counter of every page a TeX run shipped out, in order, off its `.log` — or `undefined`
 * when the log cannot be read that way.
 *
 * TeX's `ship_out` writes `[<\count0>…` into the log as it ships each page, and `]` when done, and
 * a document has no way to stop it, so the k-th mark is the counter PDF page k was shipped with
 * (verified over real pdflatex, xelatex and lualatex builds: see `test/unit/shipoutMarks.test.ts`).
 * A document CAN add text that looks like a mark (`\message{[7]}`, a box display quoting
 * "see [1]"), so the result is evidence that may only refuse a page, and its length is checked
 * against the PDF's page count before it is used at all (`labelPages.ts`).
 *
 * The log is first rejoined across TeX's 79-column hard wrap (`unwrapLines`), which can cut a
 * mark, or an image path inside one. Then the places where TeX copies the DOCUMENT's text into
 * the log are skipped, since that text can hold `see [12]`:
 *
 *  - a box display ({@link BOX_WARNING}): from its `Overfull \hbox`/`Underfull \vbox`/… line
 *    through the next empty line — every line of it, whatever it starts with (`[]`, a font
 *    `\OT1/…`, `$` for a math node, a space for glue). TeX ends every display with an empty line
 *    before anything else is written (`end_diagnostic`), and over real pdflatex, xelatex and
 *    lualatex builds that shipped a page right after a box warning the page's mark always came
 *    after that line, never inside the block. The one exception to "through the next empty
 *    line" is a warning raised inside the output routine (`… has occurred while \output is
 *    active []`), whose display is on its own line and whose ONE following empty line the
 *    79-column rejoin swallows when that line is exactly 79 columns — so it is a block of one
 *    line, and the page's mark after it is kept;
 *  - an error ({@link ERROR_START}): from its `./main.tex:3: …` line through the next empty
 *    line — its context quotes the source (`l.3 Text \foo` / `see [12] here`) and its help can be
 *    the document's own `\errhelp`. A primitive TeX error writes nothing else before that empty
 *    line; a LaTeX- or package-format error (`\GenericError`) writes an empty line right after
 *    its first line, so its context and help are then read like any other line — a known gap
 *    that can only add marks, so the length check switches the cross-check off;
 *  - outside an error, the first line of a context pair ({@link ERROR_CONTEXT}: `l.<n> …`,
 *    `<argument> …`), which a pdfTeX warning prints. Its SECOND line is read: nothing ends it, and
 *    over real pdflatex builds with hyperref the next page's mark was written onto it — so a
 *    document text quoted there still counts, and can only make the list too long;
 *  - any other line starting with `[]` or `\`, which is how a box display's own lines begin
 *    when a display turns up without its warning line.
 *
 * The one wrong VALUE this could read is a mark cut by a wrap the rejoin did not see (TeX's column count
 * and the line's length disagree when the line holds a string TeX does not count or, under LuaTeX,
 * a multi-byte character): `[12` / `3]` would read as 12. So a mark that ends its line while the
 * next line starts with a digit or a `.` gives up on the whole log, rather than read one number
 * wrong in a list of the right length. Decode the log as latin1 before calling this: pdfTeX wraps
 * at 79 BYTES, so one byte must be one character for the rejoin to see a wrapped line that holds
 * a non-ASCII file name.
 */
export function parseShipoutMarks(log: string): number[] | undefined {
  const lines = unwrapLines(log);
  const marks: number[] = [];
  // Inside a block that runs to the next empty line: a box display, or an error message with its
  // context and help.
  let inBlock = false;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!;
    if (inBlock) {
      if (line === '') inBlock = false;
      continue;
    }
    if (BOX_WARNING.test(line)) {
      inBlock = !OUTPUT_ACTIVE_BOX_WARNING.test(line);
      continue;
    }
    if (ERROR_START.test(line)) {
      inBlock = true;
      continue;
    }
    if (ERROR_CONTEXT.test(line)) continue;
    if (line.startsWith('[]') || line.startsWith('\\')) continue;
    for (const m of line.matchAll(SHIPOUT_MARK)) {
      if (m.index + m[0].length === line.length && /^[0-9.]/.test(lines[i + 1] ?? '')) {
        return undefined;
      }
      marks.push(Number(m[1]));
    }
  }
  return marks;
}

/**
 * The shipout marks ({@link parseShipoutMarks}) of the `.log` beside `auxPath` (same job name),
 * or `undefined` when there is none, it is not a regular file, it is a symbolic link, it cannot be
 * read for any reason, or it is larger than {@link MAX_SHIPOUT_LOG_BYTES}. Read whole, and
 * checked to be a regular file on the open handle.
 *
 * A symbolic link at the log is refused on every platform: `lstat` first, then an open with
 * `O_NOFOLLOW` where the platform has it (not Windows, where `fs.constants.O_NOFOLLOW` is
 * undefined). Where it does not, a link planted between the `lstat` and the `open` would be
 * followed — a window this function does not close, and does not need to: the marks can only
 * ever REFUSE a label (and a list that does not number the PDF's pages is not used at all), so a
 * swapped-in file can at worst refuse a label that would have resolved, never resolve one.
 *
 * Every failure is "no marks" rather than an error, because the marks can only add a refusal: a
 * lookup without them runs exactly as it did before they were read. Kept apart from
 * {@link readPgfpagesEvidence}, whose tri-state it must not change.
 */
export async function readShipoutMarks(auxPath: string): Promise<number[] | undefined> {
  const stem = auxPath.slice(0, -path.extname(auxPath).length);
  const logPath = `${stem}.log`;
  let handle;
  try {
    if (!(await lstat(logPath)).isFile()) return undefined;
    handle = await open(logPath, fsConstants.O_RDONLY | (fsConstants.O_NOFOLLOW ?? 0));
  } catch {
    return undefined;
  }
  try {
    const st = await handle.stat();
    if (!st.isFile() || st.size > MAX_SHIPOUT_LOG_BYTES) return undefined;
    // One byte past the size the stat gave, so a log that grew since is refused rather than cut.
    const buf = Buffer.alloc(st.size + 1);
    let length = 0;
    for (;;) {
      const { bytesRead } = await handle.read(buf, length, buf.length - length, length);
      if (bytesRead === 0) break;
      length += bytesRead;
      if (length === buf.length) return undefined;
    }
    return parseShipoutMarks(buf.subarray(0, length).toString('latin1'));
  } catch {
    return undefined;
  } finally {
    await handle.close();
  }
}

/**
 * Read and parse the build-dir `.aux` for a project/root file, for `pdf_geometry`'s "floats" kind.
 * Never throws for a missing `.aux` (nothing compiled yet, or a backend that doesn't write one) —
 * that comes back as
 * `{ floats: [], omitted: 0, total: 0, dropped: 0, refused: 0, indeterminate: 0, note }`. Any
 * other read failure (e.g. unreadable permissions) propagates, since that is a real problem the
 * caller should see, not a normal "not compiled yet" state. `shipouts: true` also reads the
 * `.log`'s shipout marks into `shipouts` ({@link readShipoutMarks}) — for a label lookup, which
 * checks its resolved pages against them; the floats index does not ask.
 */
export async function readAuxFloats(
  projectDir: string,
  rootFile: string,
  opts?: { max?: number; shipouts?: boolean; buildDir?: string },
): Promise<AuxFloatsResult> {
  const max = opts?.max ?? DEFAULT_MAX_FLOATS;
  // `buildDir` reads another build of the same root — an overlay compile's variant `out/` —
  // instead of the project's own. Everything below (the \@input walk, the pgfpages evidence, the
  // shipout marks) is derived from this one path, so it all reads that build.
  const auxPath =
    opts?.buildDir !== undefined
      ? buildAuxPathIn(opts.buildDir, rootFile)
      : buildAuxPath(projectDir, rootFile);

  let auxContent: string;
  try {
    auxContent = await readFile(auxPath, 'utf8');
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
      return {
        floats: [],
        omitted: 0,
        total: 0,
        dropped: 0,
        refused: 0,
        indeterminate: 0,
        unreadInputs: 0,
        beamerNav: false,
        note:
          `No .aux found in the build directory (${toPosix(auxPath)}) — nothing has been ` +
          'compiled with this root file yet, or the compile backend in use did not write one.',
      };
    }
    throw err;
  }

  // A single pass over the whole file — and over every file it \@inputs, which is where
  // \include puts a chapter's labels (bounded per MAX_GROUP_SCAN/GROUP_SKIP_SCAN/PARSE_BOUND
  // above, never per-result, with PARSE_BOUND shared across the files) — rather than
  // parseAuxLabels + a post-hoc filter, so `total` reflects every real \newlabel in the index,
  // not just the ones that fit under an earlier, smaller parse cutoff.
  const inputWalk = await scanWithInputs(auxContent, path.basename(auxPath), path.dirname(auxPath));
  const floats: AuxLabel[] = [];
  let total = 0;
  let dropped = 0;
  let refused = 0;
  let indeterminate = 0;
  for (const outcome of inputWalk.outcomes) {
    if (outcome.kind === 'indeterminate') {
      // No key was parsed, so there is no label to test against isCleverefShadow — which is the
      // reason this is its own counter and not a `dropped`: a cleveref shadow record with an
      // unterminated key would otherwise be reported as a lost float. Counted in full.
      indeterminate++;
      continue;
    }
    if (outcome.kind === 'refused') {
      // No label was parsed, so there is nothing to test for a cleveref shadow — and nothing to
      // test it against, since the point is that these bytes are not an entry. Counted in full.
      refused++;
      continue;
    }
    if (outcome.kind === 'dropped') {
      if (!isCleverefShadow(outcome.label)) {
        dropped++;
      }
      continue;
    }
    if (isCleverefShadow(outcome.entry.label)) {
      continue;
    }
    total++;
    if (floats.length < max) {
      floats.push(outcome.entry);
    }
  }

  const note = unreadInputsNote(inputWalk);
  const pgfpages = await readPgfpagesEvidence(auxPath);
  const shipouts = opts?.shipouts === true ? await readShipoutMarks(auxPath) : undefined;
  return {
    floats,
    omitted: total - floats.length,
    total,
    dropped,
    refused,
    indeterminate,
    unreadInputs: inputWalk.unread.length,
    beamerNav: inputWalk.beamerNav,
    ...(inputWalk.beamerSlides.size > 0 ? { beamerSlides: inputWalk.beamerSlides } : {}),
    ...(pgfpages === undefined ? {} : { pgfpages }),
    ...(shipouts === undefined ? {} : { shipouts }),
    ...(note === undefined ? {} : { note }),
  };
}
