/**
 * Parse `\newlabel` entries out of a LaTeX `.aux` file, and read+filter them for `pdf_geometry`'s
 * "floats" index.
 *
 * This file is document-controlled: an `.aux` is generated by the LaTeX run, but its content
 * (label keys, printed numbers) ultimately comes from the document's own `\label`/`\ref` macros
 * and packages, so it must be treated the same way CLAUDE.md treats a compile log — never opened,
 * resolved, stat'd, or otherwise acted on as a path, and never interpolated into a shell command.
 * It is parsed into plain strings and returned as plain strings, nothing more. It also means a
 * malformed or hand-crafted `.aux` must never cost more than a small, constant amount of work per
 * `\newlabel` marker it contains — see `MAX_GROUP_SCAN`/`GROUP_SKIP_SCAN`/`PARSE_BOUND` below.
 */

import { readFile } from 'node:fs/promises';
import { buildAuxPath } from '../services/compiler.js';
import { toPosix } from './paths.js';

export interface AuxLabel {
  label: string;
  /** The float's printed number, e.g. "3" or "2.1" — whatever \newlabel's first group holds. */
  number: string;
  /** The printed page the label resolved to, as it appears in the .aux (may be "iv", "3"). */
  page: string;
}

const DEFAULT_MAX_LABELS = 2000;
const MAX_FIELD_LENGTH = 200;
const NEWLABEL_MARKER = '\\newlabel';

/**
 * How far `readBraceGroup` will scan looking for a matching `}` before giving up on an unbalanced
 * `{`, and — separately — the length past which a group is treated as "too long to accept",
 * even once found (see `GROUP_SKIP_SCAN` below for the distinction). A real `\newlabel` group —
 * even hyperref's five-group form with a caption in the third slot — is at most a few hundred
 * characters; 4096 is generous headroom above that. Without a bound at all, an unbalanced `{`
 * (truncated file, or a hostile one) makes a single failing `readBraceGroup` call scan to
 * end-of-string: with `PARSE_BOUND`-many markers to try, that is O(n) work on EVERY failing
 * marker, i.e. O(n^2) overall (measured: 520KB of unbalanced markers took 27s). Capping the scan
 * turns each marker's worst case into O(MAX_GROUP_SCAN) — a constant — so the whole file is O(n)
 * regardless of how it is malformed. Exported so a test can build inputs that land exactly on the
 * accept/drop boundary rather than duplicating this magic number.
 */
export const MAX_GROUP_SCAN = 4096;

/**
 * A second, larger scan budget used ONLY to locate — never to accept — the true end of a group
 * whose content exceeds `MAX_GROUP_SCAN`. Why this exists: "always advance past an abandoned
 * group" (see `scanAuxEntries` below) is not safe if "abandoned" only means "past
 * `MAX_GROUP_SCAN`" — a real hyperref caption can clear `MAX_GROUP_SCAN` by a modest margin
 * (measured: a 4200-character caption lands about 180 characters past it), and advancing only to
 * `MAX_GROUP_SCAN`'s own limit resumes the scan partway through the group's own content, right in
 * reach of any `\newlabel`-shaped text still inside it — reintroducing the exact fabricated-entry
 * bug this whole mechanism exists to prevent. `GROUP_SKIP_SCAN` gives the scanner room to find
 * that group's real closing brace (so it can jump cleanly past everything inside it, including a
 * `\newlabel`-shaped substring) without ever accepting the group's content as a parsed entry —
 * length is still checked against `MAX_GROUP_SCAN` for that decision, so a well-formed-but-long
 * group is still reported as `dropped` (see `AuxFloatsResult`), never silently parsed past the
 * accepted length, and never silently lost either.
 *
 * Still a FIXED constant, so the linearity guarantee is untouched: a group whose true end is
 * never found even within `GROUP_SKIP_SCAN` (`readGroupOrSkip`'s `'exhausted'`) costs at most
 * `MAX_GROUP_SCAN + GROUP_SKIP_SCAN` — still O(1) per marker, regardless of `aux.length`. Whether
 * `scanAuxEntries` advances `searchFrom` past that outcome depends on WHY it failed
 * (`readGroupOrSkip`'s own doc has the detail): when the retry itself ran off the true end of the
 * file (`reason: 'truncated'`), it does not — there is nothing left to find, so leaving
 * `searchFrom` alone risks nothing and forgoes nothing. It does still open an `OpenSpan` there
 * (see `scanAuxEntries`), which costs nothing and is not an advance: a walk that reached
 * end-of-file without the depth ever touching 0 has PROVEN the group is open at every position
 * after `start`, so every later marker is inside it. When the retry was itself budget-exhausted
 * (`reason: 'tooLong'`, more of the file remains beyond `GROUP_SKIP_SCAN`), it DOES advance, to
 * exactly as far as this call already scanned (`start + GROUP_SKIP_SCAN`) — not a guess, since
 * every character up to there was read looking for the closing brace. Total work across a whole
 * file stays bounded by `PARSE_BOUND * (MAX_GROUP_SCAN + GROUP_SKIP_SCAN)` — a small constant —
 * never by the number of markers squared, regardless of which of the two paths above is taken.
 *
 * Advancing to `start + GROUP_SKIP_SCAN` is where this constant stops being enough on its own,
 * and why `scanAuxEntries` also keeps an OPEN SPAN (see `OpenSpan` below) for the `'tooLong'`
 * case. Jumping there says nothing about the text BEYOND it: the group is still open, so a
 * `\newlabel`-shaped string sitting further inside it than this budget reaches is the next thing
 * `indexOf` finds, and used to be reported as a real label — issue #80 §3. Raising the constant
 * only moves that boundary; nothing finite removes it. What removes it is continuing the same
 * brace walk past the budget, one stretch at a time, and that is what the open span does.
 *
 * Exported for the same reason `MAX_GROUP_SCAN` is: so a test can build an input that lands
 * exactly on this boundary rather than re-deriving the number and silently drifting off it.
 */
export const GROUP_SKIP_SCAN = MAX_GROUP_SCAN * 4;

/**
 * Hard cap on how many `\newlabel` markers a single scan (`parseAuxLabels` or `readAuxFloats`)
 * will ever inspect, enforced by a loop counter that is INDEPENDENT of how many entries parse
 * successfully — unlike the old `while (results.length < maxLabels)` guard, which only advanced
 * on a successful parse, so a file that is mostly failing markers never made progress toward its
 * own bound. Each marker's own cost is already bounded by `MAX_GROUP_SCAN`/`GROUP_SKIP_SCAN`
 * above, so this is a second, independent line of defense: even at the worst case (every marker
 * unbalanced, every group scan burning its full budget), total work is bounded by
 * `PARSE_BOUND * (MAX_GROUP_SCAN + GROUP_SKIP_SCAN)` — a constant, not something that grows with
 * file size. 50000 is well above any real document: `readAuxFloats`'s `total`/`omitted` (see
 * `AuxFloatsResult`) are exact against the TRUE count of `\newlabel` markers in the file as long
 * as the file contains at most this many; past it, both saturate at what this bound allows, same
 * as any bounded scan must — the module doc comment above is why a bound exists at all. Exported
 * so a test can exercise the exact boundary rather than duplicating a magic number that could
 * silently drift out of sync.
 */
export const PARSE_BOUND = 50_000;

/**
 * A scan-work accumulator: the number of CHARACTERS of `aux` this scan has looked at — every
 * character the `indexOf` pass walks over on its way to a marker, every character a brace walk
 * (`scanBalance`) steps through, and every character `skipWs` runs past. It exists for exactly one
 * reason: the guarantee this whole module is built around is that total work stays LINEAR in
 * `aux.length` no matter how the file is malformed, and a test can only hold that guarantee by
 * measuring the work. Measuring it with `Date.now()` was tried first and flaked — at the input
 * sizes these bounds make cheap, a single-digit-millisecond sample is dominated by scheduler
 * jitter and GC from the rest of a parallel test run, so a genuinely linear scan read 3.2x while
 * the threshold separating linear (~2x) from quadratic (~4x) sat at 3.0 (issue #173). A character
 * count is exactly the quantity those bounds bound, is identical on every machine and under any
 * load, and is inflated precisely by the mistake being guarded against: re-walking a group from
 * its start for every marker reads the same characters over and over, and the counter says so.
 *
 * It is threaded as an optional parameter and is `undefined` on every production path — the only
 * way to obtain one is `measureAuxScanWork`, a separate export that no ordinary caller reaches, so
 * there is no option a caller of `parseAuxLabels`/`readAuxFloats` could leave switched on. Nothing
 * here logs (stdout is the JSON-RPC channel, and this would not even earn a stderr line); it only
 * adds to a number. Counting is done by arithmetic at each scan's exit (`i - from`), never a
 * per-character increment, so the hot loops keep their shape whether or not one is passed.
 */
interface ScanWork {
  /** Characters examined so far. Monotonically increasing; never reset mid-scan. */
  steps: number;
}

/**
 * The one home of the brace-balance rules — `{` opens, `}` closes, and a backslash escapes
 * whatever follows it so a literal `\{`/`\}` never perturbs the count — factored out of
 * `readBraceGroup` so a walk can be RESUMED rather than restarted. `readBraceGroup` runs it over
 * one budgeted window; `scanAuxEntries` continues that very same walk over the text after a
 * window that ran out (see `OpenSpan`). Two properties make resuming safe and cheap, and both
 * come from this being one function rather than two implementations of the same rules:
 *
 * - `next` is the index to resume at, which is one PAST `to` when an escape straddled the
 *   boundary (the `\` was consumed at `to - 1`, so the character it escapes must not be re-read
 *   as a brace). A second, independent scanner would get this wrong in exactly the way that turns
 *   an escaped brace into a real one.
 * - `next` only ever moves forward, so continuing a walk reads each character of the file at most
 *   once no matter how many times it is continued.
 *
 * Scans `[from, to)` (clamped to `s.length`) starting at brace depth `depth`. `'closed'` means the
 * depth reached 0 and `end` is the index just past the closing `}`; `'open'` means the window ran
 * out first, and carries the state to pick the walk up again. An `'open'` depth is always >= 1: a
 * depth reaching 0 returns `'closed'` instead, and it can never step below 0 without passing
 * through it.
 */
function scanBalance(
  s: string,
  from: number,
  to: number,
  depth: number,
  work?: ScanWork,
): { kind: 'closed'; end: number } | { kind: 'open'; depth: number; next: number } {
  let d = depth;
  let i = from;
  const limit = Math.min(s.length, to);
  for (; i < limit; i++) {
    const ch = s[i];
    if (ch === '\\') {
      // Skip an escaped character (e.g. `\{`, `\}`) so it never perturbs the brace count.
      i++;
      continue;
    }
    if (ch === '{') {
      d++;
    } else if (ch === '}') {
      d--;
      if (d === 0) {
        if (work) work.steps += i + 1 - from;
        return { kind: 'closed', end: i + 1 };
      }
    }
  }
  if (work) work.steps += Math.max(0, i - from);
  return { kind: 'open', depth: d, next: i };
}

/**
 * A brace-balanced reader over `s` starting just after an opening `{` at `start` (i.e. `s[start]`
 * must be `{`). On success, returns the group's raw content (excluding the outer braces) and the
 * index just past the matching closing `}`. On failure, reports WHY, because the two reasons
 * demand different handling from the caller (see `readGroupOrSkip`/`scanAuxEntries` below):
 * `'unbalanced'` means the scan reached the true end of `s` (or of the caller-supplied window)
 * without ever balancing — a truncated or malformed marker, and there is nothing more to find no
 * matter how far we looked; `'budgetExhausted'` means the scan hit `maxScan` characters with MORE
 * of `s` still unscanned — the group may still be perfectly well-formed, just longer than this
 * call was willing to accept. `scannedTo` is the index the scan actually reached, either way, and
 * `depth`/`next` are the underlying walk's resume state (see `scanBalance`) so a caller that has
 * to keep tracking this group past the budget continues the same walk rather than starting a
 * second one over text it has already read.
 */
function readBraceGroup(
  s: string,
  start: number,
  maxScan: number,
  work?: ScanWork,
):
  | { kind: 'ok'; content: string; end: number }
  | {
      kind: 'fail';
      reason: 'unbalanced' | 'budgetExhausted';
      scannedTo: number;
      depth: number;
      next: number;
    } {
  if (s[start] !== '{') {
    return { kind: 'fail', reason: 'unbalanced', scannedTo: start, depth: 0, next: start };
  }
  const limit = Math.min(s.length, start + maxScan);
  const walk = scanBalance(s, start, limit, 0, work);
  if (walk.kind === 'closed') {
    return { kind: 'ok', content: s.slice(start + 1, walk.end - 1), end: walk.end };
  }
  // Ran out of scan room without balancing. `limit < s.length` means more of `s` remains beyond
  // where we gave up — this call's budget was the limiting factor, not the input itself.
  const reason = limit < s.length ? 'budgetExhausted' : 'unbalanced';
  return { kind: 'fail', reason, scannedTo: limit, depth: walk.depth, next: walk.next };
}

/**
 * Wraps `readBraceGroup` for the two call sites (the key group, the outer group) that read
 * directly off the full `.aux` text rather than off an already-bounded slice of it, so a group
 * longer than `MAX_GROUP_SCAN` can still be found — and safely skipped past — rather than left to
 * wedge the scan in place or (worse) leave `\newlabel`-shaped text inside it discoverable as a
 * second, fabricated marker. See `GROUP_SKIP_SCAN`'s doc for why the retry is required, not
 * optional, and why it does not reintroduce the quadratic behavior `MAX_GROUP_SCAN` exists to
 * prevent.
 *
 * - `'ok'`: closed within `MAX_GROUP_SCAN` — an ordinary, acceptable group.
 * - `'tooLong'`: did NOT close within `MAX_GROUP_SCAN`, but did close within the larger
 *   `GROUP_SKIP_SCAN` retry — a well-formed group, just longer than we accept. `end` is its TRUE
 *   end, so the caller can jump cleanly past all of it (including anything `\newlabel`-shaped
 *   inside), never just past the smaller budget's own limit.
 * - `'unbalanced'`: the ORDINARY (`MAX_GROUP_SCAN`) attempt ran off the true end of `s` without
 *   balancing — genuinely truncated/malformed, not merely long. No retry is attempted: there is
 *   provably no closing brace left to find, and the caller must NOT advance `searchFrom` past
 *   this failure, because nothing was located to advance TO. It carries `depth`/`next` anyway,
 *   and `depth` is the discriminator the caller needs:
 *     - `depth >= 1` — a `{` WAS opened at `start` and the walk proved it is still open at
 *       end-of-file (see `scanBalance`: a depth reaching 0 returns `'closed'`), so every marker
 *       after it is inside it and `scanAuxEntries` opens an `OpenSpan` to refuse them.
 *     - `depth === 0` — `s[start]` was not a `{` at all, so no group was ever opened. This says
 *       nothing whatever about the text that follows and must NEVER open a span.
 * - `'exhausted'`: the ordinary attempt was budget-exhausted (more of `s` remained) AND the
 *   `GROUP_SKIP_SCAN` retry ALSO failed to find a closing brace. Its true end is genuinely
 *   unknown, but WHY the retry failed still matters, so this carries its own `reason`:
 *     - `reason: 'truncated'` — the retry itself ran off the true end of `s` without balancing.
 *       Exactly like the ordinary `'unbalanced'` case above, just discovered later: there is
 *       provably nothing more to find, so the caller must not "advance" past it (there is nothing
 *       there to skip past) — and, on the same proof, it opens an `OpenSpan` just the same.
 *     - `reason: 'tooLong'` — the retry was ITSELF budget-exhausted (more of `s` remains beyond
 *       `GROUP_SKIP_SCAN`). The group's true end is still unknown, but every character up to
 *       `scannedTo` (`start + GROUP_SKIP_SCAN`) WAS linearly read for brace-balance, so nothing in
 *       `[start, scannedTo)` is unexplored text — advancing the search there (rather than leaving
 *       it at `start`) skips only text this call already looked at, never a guess. See
 *       `scanAuxEntries`'s own doc for how the two are used differently.
 *
 * `'exhausted'` and `'unbalanced'` both carry `depth`/`next`, the walk's resume state, and every
 * outcome that opens a group has a use for it. Under `'tooLong'` the group is still open at
 * `scannedTo` and the file continues past it, so `scanAuxEntries` keeps walking the SAME group
 * from there (see `OpenSpan`) rather than treating everything past the budget as text outside it.
 * Under `'truncated'` (and `'unbalanced'` with `depth >= 1`) the walk already reached the true end
 * of `s`, so `next` sits at end-of-file and the resumed walk is a no-op that can never close —
 * which is precisely the wanted answer, delivered at O(1) per later marker: the group is open
 * everywhere after `start`, so everything that follows is refused.
 */
function readGroupOrSkip(
  s: string,
  start: number,
  work?: ScanWork,
):
  | { kind: 'ok'; content: string; end: number }
  | { kind: 'tooLong'; content: string; end: number }
  | { kind: 'unbalanced'; depth: number; next: number }
  | {
      kind: 'exhausted';
      reason: 'truncated' | 'tooLong';
      scannedTo: number;
      depth: number;
      next: number;
    } {
  const primary = readBraceGroup(s, start, MAX_GROUP_SCAN, work);
  if (primary.kind === 'ok') {
    return primary;
  }
  if (primary.reason === 'unbalanced') {
    // depth/next are the walk's own state, and `depth` is what tells "a `{` was opened here and
    // never closes anywhere in `s`" (>= 1) from "there was no `{` here at all" (0). Only the
    // former is evidence about the text that follows.
    return { kind: 'unbalanced', depth: primary.depth, next: primary.next };
  }
  const retry = readBraceGroup(s, start, GROUP_SKIP_SCAN, work);
  if (retry.kind === 'ok') {
    return { kind: 'tooLong', content: retry.content, end: retry.end };
  }
  return {
    kind: 'exhausted',
    reason: retry.reason === 'unbalanced' ? 'truncated' : 'tooLong',
    scannedTo: retry.scannedTo,
    depth: retry.depth,
    next: retry.next,
  };
}

/**
 * A group `readGroupOrSkip` left OPEN: no scan budget found its closing brace. Two shapes reach
 * here, and both are carried the same way.
 *
 * - The file continues past where the retry gave up (`'exhausted'` + `reason: 'tooLong'`). The
 *   group MIGHT still close, so the walk is carried forward marker by marker to find out, and a
 *   marker after the close is parsed normally.
 * - The walk ran to the TRUE end of the file without the depth ever touching 0
 *   (`'exhausted'` + `reason: 'truncated'`, and plain `'unbalanced'` with `depth >= 1`). The group
 *   provably never closes, the carried walk is a no-op, and every later marker is refused.
 *
 * Either way it holds the brace walk's resume state, so `scanAuxEntries` can keep walking that
 * one group forward instead of guessing where it ends.
 *
 * Why this is needed at all: advancing `searchFrom` to `start + GROUP_SKIP_SCAN` protects only
 * the text the retry actually read. Everything past it is still inside the group, and a
 * `\newlabel`-shaped string there was the next thing `indexOf` found — reported as a real label,
 * off a `.aux` that is document-controlled, which `render_pages` would then resolve to a page and
 * render with confidence (issue #80 §3). It cannot be closed by skipping ahead: the group's end
 * is genuinely unknown, and skipping on a guess would swallow a legitimate separate `\newlabel`
 * in text nobody ever scanned. So the span is carried instead of jumped.
 *
 * Cost, which is the whole reason this is a resumable cursor and not a re-scan: the walk is
 * continued only as far as the NEXT marker, and `next` never moves backwards, so every character
 * of the file is walked at most once across all continuations — one extra linear pass at worst,
 * on top of the `indexOf` pass `scanAuxEntries` already makes. Continuing to end-of-file instead,
 * to prove up front whether the group ever closes, is the obvious alternative and is exactly the
 * quadratic blowup `MAX_GROUP_SCAN` exists to prevent (520KB of unbalanced markers took 27s of
 * blocked event loop inside `runExclusive`): each of `PARSE_BOUND`-many markers would pay a
 * scan over the whole remaining file.
 *
 * At most one span is ever open: it is set only on the branches that `continue` immediately, and
 * the next marker either closes it or is refused under it, so a new group is never read while one
 * is outstanding.
 */
interface OpenSpan {
  /** Brace depth the walk had reached at `next`. Always >= 1 — see `scanBalance`. */
  depth: number;
  /** Where to resume the walk; may be one past the budget when an escape straddled it. */
  next: number;
}

/** Skip whitespace (including newlines — a `\newlabel` can be wrapped across lines) from `i`. */
function skipWs(s: string, i: number, work?: ScanWork): number {
  let j = i;
  while (j < s.length && /\s/.test(s[j] ?? '')) j++;
  if (work) work.steps += j - i;
  return j;
}

/**
 * One marker's outcome from `scanAuxEntries`: a successfully-parsed entry, or one of three
 * countable ways it did not become one. Every OTHER failure — a `\newlabel` not followed by a
 * `{` at all, an outer group that is truly unbalanced (not merely long), or a missing
 * number/page group — stays a silent skip, exactly as `parseAuxLabels`'s contract has always
 * been for a malformed marker. `'dropped'` covers the cases where we DO have a real, located
 * label but no valid `AuxLabel` to report for the entry as a whole:
 *   - `reason: 'fieldTooLong'` — the whole entry parsed cleanly, but label, number or page
 *     exceeded the per-field length cap (`MAX_FIELD_LENGTH`).
 *   - `reason: 'groupTooLong'` — the KEY parsed normally (short enough to accept), but the outer
 *     group (holding number/page/caption) exceeded `MAX_GROUP_SCAN` before a matching `}` was
 *     found. Its true end may have been LOCATED via the `GROUP_SKIP_SCAN` retry
 *     (`readGroupOrSkip`'s `'tooLong'`) or not even that (`'exhausted'`) — either way there is no
 *     usable number/page, but the label itself is real and known, so `label` carries it.
 *   - `reason: 'keyTooLong'` — the KEY group itself exceeded `MAX_GROUP_SCAN`, located only via
 *     the `GROUP_SKIP_SCAN` retry (`readGroupOrSkip`'s `'tooLong'` on the key). There is no
 *     genuinely usable label here (an implausible multi-KB key is not a real label), but its
 *     literal text is still reported as `label` — same as `keyGroup.content` is used for
 *     `'groupTooLong'` — purely so a cleveref `@cref`-suffixed key (implausible, but not
 *     impossible to craft) is still excluded from the count the same way an ordinary one is; see
 *     `scanAuxEntries` for where this is produced.
 * All three are countable — see `AuxFloatsResult.dropped` — because in every one of them there IS
 * a real `\newlabel` marker, with a real and known label, that the caller is choosing not to
 * report. A marker whose KEY never closed has no such label and is a different outcome again —
 * see `'indeterminate'` below.
 *
 * `'refused'` is a THIRD thing, and deliberately not a `'dropped'` with another reason. A
 * `'dropped'` says "there was a real `\newlabel` entry here and you are not getting it" — a loss
 * the caller suffers. A `'refused'` says the opposite: a `\newlabel`-shaped string was found
 * inside a group whose end could not be verified (see `OpenSpan`), so it is almost certainly not
 * an entry at all but text inside another entry's group, and it was declined rather than
 * believed. Counting the two together would report a fabrication we refused as an entry the
 * caller lost — naming a cause that did not fire, which is the overclaim this file's comments
 * guard against, and the same reason `pdf_geometry` keeps `floatsOmittedBySize` apart from
 * `floatsOmitted` and `floatsDropped`. It carries no label, because nothing about it was parsed:
 * treating its bytes as a label would be the very fabrication being refused.
 *
 * `'indeterminate'` is a FOURTH thing, and it is neither of the other two. It is yielded when a
 * marker's own KEY group was opened (`\newlabel` IS followed by a `{`) but its closing brace was
 * never located: `readGroupOrSkip`'s `'exhausted'` on the key under either reason, or its
 * `'unbalanced'` with `depth >= 1`. The claim it makes is deliberately the weakest of the four —
 * a `\newlabel` marker existed here and we can say NOTHING about it.
 *
 * Not `'dropped'`, which says "there was a real entry and you are not getting it": there is no
 * key text here to know that with, and with no key there is nothing to test `isCleverefShadow`
 * against — so folding it into `dropped` would report a cleveref shadow record (not a float, and
 * excluded from every count in this file) as a lost float. Not `'refused'` either, which says
 * the opposite thing: that nothing is missing, because the bytes were never an entry. Before
 * this outcome existed such a marker produced no outcome at all and vanished with
 * `total`/`dropped`/`refused` all 0 — issue #139 §2, the key-side remainder of #76's FINDING 2.
 * It carries no label for the same reason `'refused'` does not: there is no parsed key to carry,
 * and inventing one from the unterminated bytes is the fabrication this file exists to refuse.
 *
 * The one key-side failure that stays a silent skip is `depth === 0` — `\newlabel` followed by
 * something that is not a `{` at all. Nothing was opened, so there is no evidence a `\newlabel`
 * INVOCATION was ever there (the bytes may be prose, or `\newlabelfoo`), and counting it would
 * put a number on text rather than on a marker. Length is deliberately NOT the line: a key
 * `{` that never closes is `'unbalanced'` when the file ends within `MAX_GROUP_SCAN` of it and
 * `'exhausted'` when it does not, and a counter that fired only past 4096 characters would be
 * drawing a distinction no caller could act on.
 */
type ScanOutcome =
  | { kind: 'entry'; entry: AuxLabel }
  | { kind: 'dropped'; label: string; reason: 'fieldTooLong' | 'groupTooLong' | 'keyTooLong' }
  | { kind: 'refused' }
  | { kind: 'indeterminate' };

/**
 * The shared scan behind both `parseAuxLabels` and `readAuxFloats`: walks `aux` for `\newlabel`
 * markers, yielding one outcome per marker that is not a silent skip (see `ScanOutcome` for
 * which failures are which). Bounded on two independent axes (see
 * `MAX_GROUP_SCAN`/`GROUP_SKIP_SCAN`/`PARSE_BOUND` above) so total work
 * is linear in `aux.length` no matter how the file is malformed — none of these bounds depend on
 * how many outcomes the caller actually consumes, so a caller that stops early (`parseAuxLabels`,
 * once it has `maxLabels` entries) does strictly less work, never more.
 *
 * Advances `searchFrom` past a group's end WHENEVER that end is actually known, never on a guess:
 *   - `'ok'`/`'tooLong'` (either the key or the outer group): the marker has consumed that whole
 *     span either way, so re-entering it would let a `\newlabel`-shaped string INSIDE it (e.g. in
 *     hyperref's caption group, or even inside an implausibly long key) be picked up as a second,
 *     fabricated entry — so `searchFrom` always jumps to (at least) the key's own end the moment
 *     the key is located, and to the outer group's end once that is located too.
 *   - `'exhausted'` with `reason: 'tooLong'`: the group's true end is still unknown, but
 *     `readGroupOrSkip` already linearly scanned every character up to `scannedTo`
 *     (`start + GROUP_SKIP_SCAN`) looking for it — so advancing `searchFrom` there is NOT a guess
 *     either, it only skips text this call already read. This closes the fabrication risk for any
 *     `\newlabel`-shaped substring located anywhere within that scanned span, not merely near its
 *     start — before this, not advancing at all left the WHOLE remaining group vulnerable
 *     regardless of where inside it a fake marker sat. Advancing says nothing about the text
 *     BEYOND the budget, though, which is why the same branch also opens an `OpenSpan`: the group
 *     is still open there, and the walk is carried forward marker by marker rather than the group
 *     being declared over (issue #80 §3 — this used to be the residual, and a `\newlabel`-shaped
 *     string more than `GROUP_SKIP_SCAN` characters into the group came back as a real label).
 *   - `'exhausted'` with `reason: 'truncated'`, or plain `'unbalanced'` with `depth >= 1`: the
 *     retry (or the primary attempt) ran off the TRUE end of `aux` without ever finding a closing
 *     brace — there is provably nothing left to find no matter how far we looked, so `searchFrom`
 *     is left wherever it already is (which may still be past the key, if the key itself was
 *     located). Nothing is advanced on these branches; an `OpenSpan` is opened instead, and the
 *     paragraph below is why.
 *
 * While an `OpenSpan` is outstanding, every marker is first resolved AGAINST it: the brace walk
 * is continued from where it stopped to the marker's own index, which either finds the group's
 * close first (the span is over, the marker is ordinary text after it, and it is parsed
 * normally) or does not (the marker is inside the group, and is `'refused'` — never reported,
 * always counted). Here the file continues and the check costs only the characters between two
 * markers, so the fabrication is refusable — and a marker is refused even though the walk may
 * later turn out never to close at all, because the `.aux` is document-controlled and a
 * fabricated label becomes a page `render_pages` renders with confidence, whereas a refused one
 * is a counted gap.
 *
 * There used to be an ASYMMETRY here, and it is gone: a group that closes nowhere in the file
 * was left reportable, so a `\newlabel`-shaped string sitting after it came back as a real entry
 * (issue #80 §3's last sub-case, #139 §1). Two things were wrong with it, in order of
 * importance.
 *
 * The evidence is not absent. On these branches the walk reached the TRUE end of `aux` without
 * the depth ever touching 0, which (see `scanBalance`: a depth reaching 0 returns `'closed'`)
 * PROVES the group is open at every position from `start` to end-of-file. So every later marker
 * is provably inside another entry's argument, and establishing that costs nothing at all — the
 * walk has already been paid for. The comment that once justified the asymmetry with "there is
 * no cheap check left to make" was simply false, and was corrected in #133 before the decision
 * itself was revisited.
 *
 * What actually held it up was a RECALL bet — a corrupt or truncated `.aux` tail probably still
 * holds legitimate records, so keep reporting them — and the repository owner reversed that bet
 * in #139. This module feeds label→page lookup in `render_pages` and `extract_text`, so a
 * fabricated label whose key happens to collide with a requested one resolves to a page the tool
 * then renders WITH CONFIDENCE, off bytes the document itself controls. That is the failure
 * shape the rest of this codebase refuses by construction — `approximate: true` meaning "never
 * use this for a collision computation", a source snippet shown only where its location can be
 * vouched for, `peerEntries` returning `null` for an unreadable index and never "owns nothing",
 * and `refused` itself existing so a declined fake is never miscounted as a missing entry. A
 * counted gap is recoverable; a confident wrong page is not.
 *
 * The recall cost is smaller than it reads, which is part of why the trade flipped. The markers
 * a span now refuses are only those AFTER an unclosed group — and in the shape the bet was made
 * for, an `.aux` cut off mid-write by a killed `latexmk`, the unclosed group IS the last thing
 * in the file, so nothing follows it to refuse. What is given up is recall on a file where a
 * group opens, never closes, and legitimate entries follow it anyway: a file no honest LaTeX run
 * produces. What is bought is that no such file can invent a page number.
 *
 * Every `readGroupOrSkip` call is itself O(1)-bounded regardless of outcome, and the open-span
 * walk reads each character of `aux` at most once across all of its continuations (`next` never
 * moves backwards), so total work stays `O(aux.length) + PARSE_BOUND * (MAX_GROUP_SCAN +
 * GROUP_SKIP_SCAN)` — the same linear bound as before, a pass over `aux` being what `indexOf`
 * already costs. Per marker the span check is amortized O(1) rather than worst-case O(1): a
 * marker far from the previous one pays for the gap, and the markers that gap contains do not
 * exist to pay for it.
 */
function* scanAuxEntries(aux: string, work?: ScanWork): Generator<ScanOutcome> {
  let searchFrom = 0;
  let scans = 0;
  let openSpan: OpenSpan | null = null;
  while (scans < PARSE_BOUND) {
    const markerIdx = aux.indexOf(NEWLABEL_MARKER, searchFrom);
    if (markerIdx === -1) {
      // The search still read everything left of end-of-file looking for one.
      if (work) work.steps += Math.max(0, aux.length - searchFrom);
      break;
    }
    // `indexOf` looked at every character from `searchFrom` through the end of the match.
    if (work) work.steps += markerIdx + NEWLABEL_MARKER.length - searchFrom;
    scans++;
    // Advance past this marker regardless of what happens below, so a malformed entry cannot
    // wedge the scan in place.
    searchFrom = markerIdx + NEWLABEL_MARKER.length;

    if (openSpan) {
      // Carry the abandoned group's own brace walk forward to this marker — never past it, so
      // the cost is the gap between two markers and each character is walked at most once.
      const walk = scanBalance(aux, openSpan.next, markerIdx, openSpan.depth, work);
      if (walk.kind === 'closed') {
        // The group ended before this marker, so the marker is ordinary text that follows it:
        // the span is over and the marker gets the normal treatment below.
        openSpan = null;
      } else {
        // Still inside the group. This is `\newlabel`-shaped text sitting in another entry's
        // argument, not an entry — refuse it rather than fabricate a label (and a page) from it.
        openSpan = { depth: walk.depth, next: walk.next };
        yield { kind: 'refused' };
        continue;
      }
    }

    let i = skipWs(aux, searchFrom, work);
    const keyGroup = readGroupOrSkip(aux, i, work);
    if (keyGroup.kind === 'unbalanced') {
      if (keyGroup.depth > 0) {
        // A `{` was opened for the key and the walk proved it never closes anywhere in the file.
        // searchFrom is NOT advanced (nothing was located to advance to), but everything after
        // this point is provably inside that group, so carry it as a span and refuse what
        // follows rather than reading it as entries of its own.
        openSpan = { depth: keyGroup.depth, next: keyGroup.next };
        yield { kind: 'indeterminate' };
      }
      // depth 0: `\newlabel` was not followed by a `{` at all. Nothing was opened, so this says
      // nothing about the text after it — no span, and nothing to count. Silent skip, as always.
      continue;
    }
    if (keyGroup.kind === 'exhausted') {
      if (keyGroup.reason === 'tooLong') {
        // Not a guess — scannedTo is exactly how far this call already read; see this function's
        // own doc for why that makes advancing here safe rather than a risk.
        searchFrom = keyGroup.scannedTo;
      }
      // Either reason: the group is still open at `next`, so keep walking it rather than
      // treating whatever follows as text outside it. Under 'tooLong' the file continues and the
      // walk may yet find the close; under 'truncated' it reached end-of-file already and the
      // carried walk is a no-op that can never close, which is the answer wanted.
      openSpan = { depth: keyGroup.depth, next: keyGroup.next };
      // A real \newlabel marker was here and its key never closed, so there is no label to
      // report and nothing to test for a cleveref shadow. Counted as its own outcome rather than
      // vanishing (#139 §2) — see ScanOutcome for why it is neither a drop nor a refusal.
      yield { kind: 'indeterminate' };
      continue;
    }

    // keyGroup is 'ok' or 'tooLong' — either way its end is real and known, so it is always safe
    // to resume from there even if everything that follows (the outer group) turns out malformed.
    const keyTooLong = keyGroup.kind === 'tooLong';
    const keyContent = keyGroup.content;
    searchFrom = keyGroup.end;

    i = skipWs(aux, keyGroup.end, work);
    const outerGroup = readGroupOrSkip(aux, i, work);
    if (outerGroup.kind === 'unbalanced') {
      // Truly no closing brace anywhere in the rest of the file for this group. searchFrom stays
      // at the key's own (already-known-safe) end from above; nothing further is located. But
      // when a `{` WAS opened (depth >= 1), the walk has proven it stays open to end-of-file, so
      // every later marker is inside it: carry the span. depth 0 means there was no group here
      // at all (nothing followed the key), which is evidence about nothing.
      if (outerGroup.depth > 0) {
        openSpan = { depth: outerGroup.depth, next: outerGroup.next };
      }
      continue;
    }
    if (outerGroup.kind === 'exhausted') {
      if (outerGroup.reason === 'tooLong') {
        searchFrom = outerGroup.scannedTo;
      }
      // Either reason opens the span, for the reason the key's own branch above records: under
      // 'truncated' searchFrom stays at keyGroup.end and the group is proven open from here to
      // end-of-file, so what follows is another entry's argument, not entries.
      openSpan = { depth: outerGroup.depth, next: outerGroup.next };
      // The key DID parse — there is a real label here — so this is no longer a silent skip: the
      // caller gets a countable 'dropped' outcome instead of the entry simply vanishing.
      yield {
        kind: 'dropped',
        label: keyContent,
        reason: keyTooLong ? 'keyTooLong' : 'groupTooLong',
      };
      continue;
    }
    if (outerGroup.kind === 'tooLong') {
      // A well-formed \newlabel whose outer group is longer than MAX_GROUP_SCAN accepts. We
      // found its TRUE end via the GROUP_SKIP_SCAN retry, so jump cleanly past the whole group —
      // including anything \newlabel-shaped inside it — instead of resuming partway through it.
      searchFrom = outerGroup.end;
      yield {
        kind: 'dropped',
        label: keyContent,
        reason: keyTooLong ? 'keyTooLong' : 'groupTooLong',
      };
      continue;
    }
    // outerGroup.kind === 'ok'. The whole outer group has been consumed either way (success or a
    // downstream field-shape failure below) — jump past it so nothing inside it is ever
    // re-entered as its own marker.
    searchFrom = outerGroup.end;

    if (keyTooLong) {
      // Both groups are now fully located and consumed cleanly, but the key itself was never a
      // usable label (see the ScanOutcome doc for what `keyContent` holds and why it is still
      // worth reporting).
      yield { kind: 'dropped', label: keyContent, reason: 'keyTooLong' };
      continue;
    }

    // The outer group's content starts with two brace groups: {number}{page}[...]. Read them with
    // the same balanced reader, ignoring anything after (hyperref appends {\relax }{anchor}{}).
    // This content is already bounded to at most MAX_GROUP_SCAN characters (outerGroup succeeded
    // under that budget to get here), so these two reads can never themselves hit a scan budget —
    // only genuine unbalance is possible, and that stays a silent skip as it always has.
    const inner = outerGroup.content;
    let j = skipWs(inner, 0, work);
    const numberGroup = readBraceGroup(inner, j, MAX_GROUP_SCAN, work);
    if (numberGroup.kind !== 'ok') {
      continue;
    }
    j = skipWs(inner, numberGroup.end, work);
    const pageGroup = readBraceGroup(inner, j, MAX_GROUP_SCAN, work);
    if (pageGroup.kind !== 'ok') {
      continue;
    }

    const label = keyContent;
    const number = numberGroup.content;
    const page = pageGroup.content;
    if (
      label.length > MAX_FIELD_LENGTH ||
      number.length > MAX_FIELD_LENGTH ||
      page.length > MAX_FIELD_LENGTH
    ) {
      yield { kind: 'dropped', label, reason: 'fieldTooLong' };
      continue;
    }

    yield { kind: 'entry', entry: { label, number, page } };
  }
}

function collectAuxLabels(aux: string, maxLabels: number, work?: ScanWork): AuxLabel[] {
  const results: AuxLabel[] = [];

  for (const outcome of scanAuxEntries(aux, work)) {
    if (outcome.kind !== 'entry') {
      continue;
    }
    results.push(outcome.entry);
    if (results.length >= maxLabels) {
      break;
    }
  }

  return results;
}

export function parseAuxLabels(aux: string, opts?: { maxLabels?: number }): AuxLabel[] {
  return collectAuxLabels(aux, opts?.maxLabels ?? DEFAULT_MAX_LABELS);
}

/**
 * `parseAuxLabels`, plus the number of characters the scan looked at getting there — the test
 * seam for this module's linearity guarantee (see `ScanWork`). It is a SEPARATE export rather
 * than an option on `parseAuxLabels` so that nothing a production caller can pass turns
 * instrumentation on: `parseAuxLabels` and `readAuxFloats` call the scan with no accumulator at
 * all, and their behaviour and return types are untouched by this existing. It runs the same
 * `collectAuxLabels` over the same generator with the same early stop, so what it counts is the
 * work the real parse does — not a re-implementation of it, which is the one way a work counter
 * can go quietly wrong. `labels` is returned alongside `steps` so a test can assert the parse's
 * OUTCOME in the same call it measures; a measurement of a scan that stopped early for the wrong
 * reason would otherwise look like excellent linearity.
 */
export function measureAuxScanWork(
  aux: string,
  opts?: { maxLabels?: number },
): { labels: AuxLabel[]; steps: number } {
  const work: ScanWork = { steps: 0 };
  const labels = collectAuxLabels(aux, opts?.maxLabels ?? DEFAULT_MAX_LABELS, work);
  return { labels, steps: work.steps };
}

/** `pdf_geometry`'s "floats" cap — labels past this are reported as `omitted`, never silently. */
export const DEFAULT_MAX_FLOATS = 200;

/**
 * cleveref's internal shadow records: for every `\label{x}` it also writes `\newlabel{x@cref}`
 * whose "number"/"page" fields are its own bracketed cross-reference codes (e.g.
 * `[figure][1][]1` / `[1][1][]1`), not printed page numbers at all. Verified against a real
 * `pdflatex` + cleveref run (this repo's own tex install, cleveref's `\newlabel` macros in
 * cleveref.sty around `\cref@constructprefix`/`\@newl@bel`): the only shadow suffix cleveref
 * emits is `@cref` — no separate `@cref@...` sibling was found. `parseAuxLabels` itself stays
 * faithful to the file and returns these; filtering them out of the "floats" index happens here,
 * one layer up, so a caller of the pure parser still sees exactly what the `.aux` says.
 */
const CLEVEREF_SHADOW_SUFFIXES = ['@cref'];

function isCleverefShadow(label: string): boolean {
  return CLEVEREF_SHADOW_SUFFIXES.some((suffix) => label.endsWith(suffix));
}

export interface AuxFloatsResult {
  /** Real (non-shadow) labels, capped at `opts.max` (default DEFAULT_MAX_FLOATS). */
  floats: AuxLabel[];
  /** Real labels found past the `max` cap — `total - floats.length`. Exact (computed against the
   *  TRUE total in `total`, not a smaller parse-time cutoff) as long as the file contains at most
   *  `PARSE_BOUND` `\newlabel` markers; see `total`'s doc for what happens past that. */
  omitted: number;
  /** The true count of real (non-shadow), successfully-parsed labels found in the file — i.e.
   *  `floats.length + omitted`, before the `max` cap is applied. A label counted here always has
   *  a valid `AuxLabel` behind it; one dropped for an over-length field or an over-budget group
   *  (see `dropped` below) is deliberately excluded, the same way it always has been for the
   *  former. Exact for any file with at most `PARSE_BOUND` `\newlabel` markers (shadow entries
   *  included in that count, since every marker costs a scan regardless of what it turns out to
   *  be) — a document with more markers than that is far past anything real, and both `total` and
   *  `omitted` saturate at whatever `PARSE_BOUND` allowed rather than reflecting the file's actual
   *  count. */
  total: number;
  /** Real (non-shadow) `\newlabel` entries found but dropped because there was no valid
   *  `AuxLabel` to report for them — never included in `total` or `floats` either way, counted
   *  here instead so the drop is never silent. Three distinct causes land in this one count (see
   *  `ScanOutcome`'s doc for the exact mechanics of each): a field (label, number, or page)
   *  exceeded the per-field length cap (`MAX_FIELD_LENGTH`) after the entry otherwise parsed
   *  cleanly; the entry's outer group (holding number/page/caption) exceeded the `MAX_GROUP_SCAN`
   *  scan budget before a matching `}` was found, whether or not its true end was ever located;
   *  or the KEY itself exceeded `MAX_GROUP_SCAN` before a matching `}` was found for IT. All three
   *  are, from a caller's point of view, the same fact: "there was a real `\newlabel` marker here
   *  we could not give you a usable entry for." */
  dropped: number;
  /** `\newlabel`-shaped strings found INSIDE a group whose closing brace neither scan budget
   *  could locate (see `OpenSpan`), refused rather than reported. Deliberately its own count and
   *  never folded into `dropped`: `dropped` means "a real entry you are not getting", while this
   *  means the opposite — text inside another entry's argument that we declined to believe was
   *  an entry at all. Reporting a refused fabrication as a dropped entry would name a cause that
   *  did not fire. Almost always 0; a non-zero value means the `.aux` is malformed or hostile,
   *  not that the index is incomplete. Optional only so that object literals of this type
   *  written elsewhere keep compiling — `readAuxFloats` always sets it. */
  refused?: number;
  /** `\newlabel` markers whose own KEY group was opened but whose closing brace neither scan
   *  budget could locate, so nothing at all about them could be read (see `ScanOutcome`'s
   *  `'indeterminate'`). Its own count, added to NONE of the others and never folded into them:
   *  `dropped` means "a real entry is missing", `refused` means "nothing is missing, a fake was
   *  declined", and this means neither — a marker existed and we can say nothing about it. There
   *  is no key text here, so it cannot even be tested for a cleveref shadow, which is why
   *  counting it as `dropped` would be wrong rather than merely imprecise. Before #139 these
   *  markers vanished with every counter at zero. Almost always 0; a non-zero value means the
   *  `.aux` is malformed or hostile. Optional for the same reason `refused` is — `readAuxFloats`
   *  always sets it. */
  indeterminate?: number;
  /** Present only when no `.aux` was found in the build directory. */
  note?: string;
}

/**
 * Read and parse the build-dir `.aux` for a project/root file, for `pdf_geometry`'s "floats" kind.
 * Never throws for a missing `.aux` (nothing compiled yet, or a backend that doesn't write one) —
 * that comes back as
 * `{ floats: [], omitted: 0, total: 0, dropped: 0, refused: 0, indeterminate: 0, note }`. Any
 * other read failure (e.g. unreadable permissions) propagates, since that is a real problem the
 * caller should see, not a normal "not compiled yet" state.
 */
export async function readAuxFloats(
  projectDir: string,
  rootFile: string,
  opts?: { max?: number },
): Promise<AuxFloatsResult> {
  const max = opts?.max ?? DEFAULT_MAX_FLOATS;
  const auxPath = buildAuxPath(projectDir, rootFile);

  let auxContent: string;
  try {
    auxContent = await readFile(auxPath, 'utf8');
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
      return {
        floats: [],
        omitted: 0,
        total: 0,
        dropped: 0,
        refused: 0,
        indeterminate: 0,
        note:
          `No .aux found in the build directory (${toPosix(auxPath)}) — nothing has been ` +
          'compiled with this root file yet, or the compile backend in use did not write one.',
      };
    }
    throw err;
  }

  // A single pass over the whole file (bounded per MAX_GROUP_SCAN/GROUP_SKIP_SCAN/PARSE_BOUND
  // above, never per-result) rather than parseAuxLabels + a post-hoc filter, so `total` reflects
  // every real \newlabel in the file, not just the ones that fit under an earlier, smaller parse
  // cutoff.
  const floats: AuxLabel[] = [];
  let total = 0;
  let dropped = 0;
  let refused = 0;
  let indeterminate = 0;
  for (const outcome of scanAuxEntries(auxContent)) {
    if (outcome.kind === 'indeterminate') {
      // No key was parsed, so there is no label to test against isCleverefShadow — which is the
      // reason this is its own counter and not a `dropped`: a cleveref shadow record with an
      // unterminated key would otherwise be reported as a lost float. Counted in full.
      indeterminate++;
      continue;
    }
    if (outcome.kind === 'refused') {
      // No label was parsed, so there is nothing to test for a cleveref shadow — and nothing to
      // test it against, since the point is that these bytes are not an entry. Counted in full.
      refused++;
      continue;
    }
    if (outcome.kind === 'dropped') {
      if (!isCleverefShadow(outcome.label)) {
        dropped++;
      }
      continue;
    }
    if (isCleverefShadow(outcome.entry.label)) {
      continue;
    }
    total++;
    if (floats.length < max) {
      floats.push(outcome.entry);
    }
  }

  return { floats, omitted: total - floats.length, total, dropped, refused, indeterminate };
}
