/**
 * Credentials a caller pasted INTO a git URL (`https://user:token@host/repo`). A project's
 * `gitUrl` is persisted to the workspace `registry.json`, echoed in `register_project`'s result and
 * listed by `list_projects`, and `GitService.clone` writes it to the clone's `origin` — so a token
 * left inside it would be stored in plain text in two files and shown back to the model. Tokens
 * are resolved per host at git time instead (`CredentialResolver`: `tokenEnv`, the host-default
 * env var, `set_credential`, `git credential fill`).
 *
 * Only `http:`/`https:` URLs carry a secret this way. An `ssh://git@host/…` or scp-style
 * `git@host:owner/repo` names a login user, never a password, and is left byte-identical.
 * Everything but the secret (and surrounding whitespace, which is trimmed) is kept as written —
 * the URL is not re-serialised, so a host or path spelling the caller chose is never normalised
 * under them.
 *
 * **A login name is kept; only a secret is removed.** The username in an http(s) URL is not a
 * secret, and it is not inert either: `CredentialResolver` never reads it (its username is the
 * per-project `username` or the host default), but when the resolver finds no token git falls
 * through to the user's own credential helpers, and those look the credential up by host AND
 * the URL's username — Azure DevOps' default clone URL is `https://<org>@dev.azure.com/…`,
 * Bitbucket's is `https://<user>@bitbucket.org/…`. Removing the name changed which credential
 * they found. So:
 *
 * - `user:secret@` loses `:secret` and keeps `user@`;
 * - a colon-less `name@` is kept — UNLESS the name is itself an access token (`looksLikeToken`):
 *   GitHub, GitLab and others accept a token as the username alone
 *   (`https://<token>@github.com/…`), and a token is removed wherever it sits, the whole userinfo
 *   with it (`token:x-oauth-basic@` included).
 *
 * The token test errs toward removal: a login name it mistakes for a token is dropped from the
 * URL — the pre-fix behaviour, and the note says so — while a token it missed would be persisted.
 * Two kinds of name are recognised as logins before that error can happen: a name the same URL
 * already publishes as a path segment or host label (Azure DevOps' `<org>@dev.azure.com/<org>/…`
 * and `<org>@<org>.visualstudio.com`, a user's own namespace in the path) — keeping it keeps
 * nothing that is not stored anyway — and AWS CodeCommit's generated `<user>-at-<account id>`.
 *
 * The scheme is matched as a URL parser reads it, not as it is usually written: WHATWG takes
 * `https:` followed by any run of `/` and `\` (none included) as `https://`, so
 * `https:/<token>@host` and `https:\<token>@host` carry the token in the userinfo just the same.
 * When a credential is removed the separator is written back as `//`; a URL left alone is
 * returned as written.
 */

/**
 * The userinfo of an http(s) URL: everything between the scheme's slashes and the LAST `@` before
 * the authority ends (`/`, `?`, `#`, or `\`, which WHATWG treats as `/` for these schemes).
 * Greedy on purpose — a raw `@` inside a password still leaves the last one as the host
 * delimiter, as a URL parser reads it, so no fragment of the token survives. The slashes are any
 * run of `/` and `\`, none included, because that is what WHATWG accepts there (`https:/tok@h`,
 * `https:\\tok@h` and `https:tok@h` all parse with `tok` as the username).
 */
const HTTP_USERINFO = /^(https?:)([\\/]*)([^/?#\\]*)@/i;

/**
 * Documented token prefixes: GitHub (`ghp_`, `gho_`, `ghu_`, `ghs_`, `ghr_`, `github_pat_`),
 * GitLab (`glpat-`, `gloas-`, `gldt-`, `glrt-`, `glptt-`, `glcbt-`, `glft-`, `glimt-`, `glsoat-`),
 * Overleaf (`olp_`), Atlassian/Bitbucket (`ATBB`, `ATATT`), Hugging Face (`hf_`).
 */
const TOKEN_PREFIX =
  /^(gh[pousr]_|github_pat_|gl(pat|oas|dt|rt|ptt|cbt|ft|imt|soat)-|olp_|ATBB|ATATT|hf_)/;

/**
 * Characters that never appear in a login name but do in a base64 token — a Bitbucket Data Center
 * HTTP access token (`NjE0…+kB2f…`), any `…==`-padded secret. Judged on the DECODED userinfo, so
 * `%2B`/`%2F`/`%3D` count too.
 */
const BASE64_ONLY = /[+=/]/;

/**
 * The length from which a prefix-less userinfo is judged by its character mix rather than kept:
 * 20 is a legacy GitLab personal access token's whole length (a base64url `friendly_token`, no
 * prefix), and every other prefix-less token (40-hex GitHub OAuth, 52-char Azure DevOps PAT) is
 * longer. Hand-picked login names reach it rarely — and then usually as `firstname.lastname`,
 * which the character mix keeps.
 */
const OPAQUE_MIN_LENGTH = 20;

/**
 * AWS CodeCommit's HTTPS Git credential user name: the IAM user name (`[\w+=,.@-]`), `-at-`, and
 * the 12-digit account id. Generated by AWS, never a secret (the password is), and long enough
 * with a digit that the character-mix rule would otherwise drop it. `+`/`=` are judged a token
 * first (`BASE64_ONLY`), the errs-toward-removal side.
 */
const CODECOMMIT_USER = /^[\w+=,.@-]+-at-[0-9]{12}$/;

/**
 * A prefix-less token's character mix: a digit, or both letter cases. A random 20-character
 * base64url string misses a digit about one time in thirty and misses one case about one time in
 * thirty thousand, so together they catch practically all of them; a login name of that length
 * is usually lower-case words (`firstname.lastname`, `jean-baptiste.dupont`), which neither test
 * matches. A long login with a digit or CamelCase (`ContosoEngineeringTeam`) is dropped — the
 * errs-toward-removal side, whose cost is only the name.
 */
function opaqueTokenMix(s: string): boolean {
  return /[0-9]/.test(s) || (/[a-z]/.test(s) && /[A-Z]/.test(s));
}

/** `s` percent-decoded, or as written when its escapes are malformed. */
function decoded(s: string): string {
  try {
    return decodeURIComponent(s);
  } catch {
    return s;
  }
}

/**
 * Whether the rest of the URL already publishes `name` (percent-decoded): as one of the host's
 * labels (port dropped), compared case-insensitively since DNS is, or as a path segment, compared
 * EXACTLY — a path segment publishes its own spelling and no other, and a mixed-case token whose
 * lower-cased form happens to be a segment is not published by it. Not the query or the fragment.
 * `rest` is what follows the userinfo's `@`.
 */
function publishesName(rest: string, name: string): boolean {
  const beforeQuery = rest.split(/[?#]/, 1)[0]!;
  const cut = beforeQuery.search(/[/\\]/);
  const host = cut === -1 ? beforeQuery : beforeQuery.slice(0, cut);
  const pathPart = cut === -1 ? '' : beforeQuery.slice(cut + 1);
  const folded = name.toLowerCase();
  const hostLabels = host.replace(/:[0-9]*$/, '').split('.');
  if (hostLabels.some((l) => l !== '' && decoded(l).toLowerCase() === folded)) return true;
  return pathPart.split(/[/\\]/).some((seg) => seg !== '' && decoded(seg) === name);
}

/**
 * Whether a URL username is an access token rather than a login name. In order: a documented
 * token prefix; an e-mail address (its `@` percent-encoded — no token format contains `@`, and
 * `+` is common in one) is a login; a base64-only character; a name the URL already publishes in
 * its host or path (`publishesName` — keeping it keeps nothing the stored URL does not hold
 * anyway) or a CodeCommit user name is a login; a long run with a token's character mix.
 */
function looksLikeToken(user: string, rest: string): boolean {
  const name = decoded(user);
  if (TOKEN_PREFIX.test(name)) return true;
  if (name.includes('@')) return false;
  if (BASE64_ONLY.test(name)) return true;
  if (publishesName(rest, name)) return false;
  if (CODECOMMIT_USER.test(name)) return false;
  return name.length >= OPAQUE_MIN_LENGTH && opaqueTokenMix(name);
}

/** What a strip removed: a password (the username kept), or a whole userinfo that was a token. */
export type RemovedCredential = 'password' | 'token';

interface Split {
  /** The scheme and the separator as they are written back when anything is removed: `https://`. */
  scheme: string;
  user: string;
  /** Present when the userinfo had a `:` — even an empty one. */
  password?: string;
  rest: string;
}

function splitUserinfo(gitUrl: string): Split | undefined {
  const m = HTTP_USERINFO.exec(gitUrl);
  if (!m) return undefined;
  const userinfo = m[3]!;
  const colon = userinfo.indexOf(':');
  const rest = gitUrl.slice(m[0].length);
  return colon === -1
    ? { scheme: `${m[1]!}//`, user: userinfo, rest }
    : {
        scheme: `${m[1]!}//`,
        user: userinfo.slice(0, colon),
        password: userinfo.slice(colon + 1),
        rest,
      };
}

/** How a URL's userinfo is to be treated: kept as is, reduced to its user, or removed. */
function classify(split: Split): 'keep' | 'user-only' | 'remove' {
  if (split.user === '' || looksLikeToken(split.user, split.rest)) return 'remove';
  return split.password === undefined ? 'keep' : 'user-only';
}

/**
 * `gitUrl` with any http(s) secret removed, whether there was one, and what it was (see the
 * module comment for what counts).
 */
export function stripGitUrlCredentials(gitUrl: string): {
  url: string;
  stripped: boolean;
  removed?: RemovedCredential;
} {
  // Trimmed first: surrounding whitespace is never part of a remote URL (a paste artefact), and
  // left in place it defeats the `^`-anchored userinfo match, so a token in `  https://tok@…`
  // was kept and persisted. The trimmed URL is what gets registered, stripped or not.
  const trimmed = gitUrl.trim();
  const split = splitUserinfo(trimmed);
  if (split === undefined) return { url: trimmed, stripped: false };
  switch (classify(split)) {
    case 'keep':
      return { url: trimmed, stripped: false };
    case 'user-only':
      return {
        url: `${split.scheme}${split.user}@${split.rest}`,
        stripped: true,
        removed: 'password',
      };
    case 'remove':
      return { url: `${split.scheme}${split.rest}`, stripped: true, removed: 'token' };
  }
}

/**
 * `gitUrl` for display: an http(s) secret replaced by `***` (`user:***@`, or `***@` for a token
 * username), so a reader can still see that the configuration embeds a credential (and go and
 * remove it) without seeing the credential. A login name alone is shown as written.
 */
export function redactGitUrlCredentials(gitUrl: string): string {
  const trimmed = gitUrl.trim();
  const split = splitUserinfo(trimmed);
  if (split === undefined) return trimmed;
  switch (classify(split)) {
    case 'keep':
      return trimmed;
    case 'user-only':
      return `${split.scheme}${split.user}:***@${split.rest}`;
    case 'remove':
      return `${split.scheme}***@${split.rest}`;
  }
}

/**
 * The result-text sentence for a registration whose URL carried a credential, claiming only what
 * was actually removed. Names every route a token can take instead, since the next clone/push
 * will otherwise fail on auth with no hint why.
 */
export function strippedCredentialsNote(removed: RemovedCredential = 'token'): string {
  const what =
    removed === 'password'
      ? ' The gitUrl carried a password or token after the username (user:token@); it was ' +
        'removed and NOT stored — neither in the workspace registry nor in the clone’s git ' +
        'config. The username was kept.'
      : ' The gitUrl’s userinfo was an access token (token@); it was removed and NOT stored — ' +
        'neither in the workspace registry nor in the clone’s git config.';
  return (
    `${what} Supply the token another way: set_credential (stores it in the OS credential ` +
    'helper), or an env var named by `tokenEnv` (or the host default, e.g. GITHUB_TOKEN / ' +
    'OVERLEAF_GIT_TOKEN), with `username` if the host needs a specific one.'
  );
}

/**
 * The note for a caller-supplied `gitUrl` — `''` when nothing would be removed from it (or there
 * is no URL). Judged on the caller's own URL, by the same `stripGitUrlCredentials` that decides
 * what is registered, so the note and the stored URL cannot disagree.
 */
export function strippedCredentialsNoteFor(gitUrl: string | undefined): string {
  if (gitUrl === undefined) return '';
  const { removed } = stripGitUrlCredentials(gitUrl);
  return removed === undefined ? '' : strippedCredentialsNote(removed);
}
