import { describe, it, expect } from 'vitest';
import {
  shellEscapeOverriddenHint,
  shellEscapeRefusedHint,
  tikzShellEscapeHint,
} from '../../src/services/compiler.js';
import { parseLog } from '../../src/services/logParser.js';

/*
 * A refused shell command is retried with `restrictedShellEscape: true` — unless restricted shell
 * escape was ALREADY in effect for the run (a latexmkrc can turn it on; the caller did not), in
 * which case the refused command is one the allow-list does not hold and that advice sends the
 * caller round a retry that cannot work. Then only `shellEscape: true` is named. "In effect" is
 * read from the engine's own banner in the log's header (before the `**` line) and nowhere else —
 * `test/unit/r2ShellForgedBanner.test.ts` pins that a document-written line cannot decide it.
 *
 * The log lines are TeX Live 2019 pdflatex's own, run with `-shell-restricted` on a two-figure
 * TikZ-externalizing document (and wrapped at 79 columns as TeX writes them).
 */

const BANNER = String.raw`This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex 2026.6.19)  28 SEP 2026 19:31
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**two.tex
(./two.tex`;

const figureBlock = (n: number, line: number): string =>
  String.raw`===== 'mode=convert with system call': Invoking 'pdflatex -halt-on-error -inter
action=batchmode -jobname "two-figure${n}" "\def\tikzexternalrealjob{two}\input{tw
o}"' ========
runsystem(pdflatex -halt-on-error -interaction=batchmode -jobname "two-figure${n}"
 "\def\tikzexternalrealjob{two}\input{two}")...disabled (restricted).

\openout3 = ` +
  "`two.auxlock'." +
  String.raw`


./two.tex:${line}: Package tikz Error: Sorry, the system call 'pdflatex -halt-on-erro
r -interaction=batchmode -jobname "two-figure${n}" "\def\tikzexternalrealjob{two}\
input{two}"' did NOT result in a usable output file 'two-figure${n}' (expected one
 of .pdf:.jpg:.jpeg:.png:). Please verify that you have enabled system calls. F
or pdflatex, this is 'pdflatex -shell-escape'. Sometimes it is also named 'writ
e 18' or something like that. Or maybe the command simply failed? Error message
s can be found in 'two-figure${n}.log'. If you continue now, I'll try to typeset t
he picture.

See the tikz package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.${line} ...icture}\draw (0,0)--(1,1);\end{tikzpicture}

This error message was generated by an \errmessage
command, so I can't give any explicit help.
Pretend that you're Hercule Poirot: Examine all clues,
and deduce the truth by order and method.
`;

const RESTRICTED_TIKZ_LOG = [BANNER, figureBlock(0, 4), figureBlock(1, 5)].join('\n');

/** A restricted run refusing a non-allow-listed command, as pdfTeX logs it. */
const RESTRICTED_REFUSAL = String.raw`This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian)
entering extended mode
 restricted \write18 enabled.
**main.tex
(./main.tex
runsystem(epstopdf --outfile=fig-eps-converted-to.pdf fig.eps)...disabled (restricted).
`;
/** The same refusal under LuaTeX's restricted banner. */
const LUA_RESTRICTED_REFUSAL = String.raw`This is LuaHBTeX, Version 1.17.0 (TeX Live 2023)
 restricted system commands enabled.
**main.tex
(./main.tex
system(epstopdf fig.eps) disabled.
`;
/** Shell escape off altogether (`-no-shell-escape`): restricted mode WOULD run repstopdf. */
const PLAIN_REFUSAL = String.raw`runsystem(repstopdf --outfile=fig-eps-converted-to.pdf fig.eps)...disabled.
`;

const latexmk = { shellEscapeOn: false, overlay: false, backend: 'latexmk' as const };

describe('shellEscapeRefusedHint names only shellEscape when restricted mode was already on', () => {
  for (const [what, log] of [
    ['pdfTeX header banner + (restricted) refusal', RESTRICTED_REFUSAL],
    ['LuaTeX header banner + refusal', LUA_RESTRICTED_REFUSAL],
  ] as const) {
    it(`${what}: no restrictedShellEscape retry, shellEscape named with its full cost`, () => {
      const hint = shellEscapeRefusedHint(log, latexmk);
      expect(hint).toBeDefined();
      expect(hint).not.toMatch(/Retry with restrictedShellEscape/);
      expect(hint).toMatch(/Retry with shellEscape: true/);
      expect(hint).toMatch(/ARBITRARY shell commands/);
      // It does not claim the run had no shell escape at all — it had the restricted list.
      expect(hint).not.toMatch(/not even TeX's restricted allow-list/);
    });

    it(`${what}, overlay: the retry names shellEscape only`, () => {
      const hint = shellEscapeRefusedHint(log, { ...latexmk, overlay: true });
      expect(hint).toBeDefined();
      expect(hint).not.toMatch(/Retrying with restrictedShellEscape/);
      expect(hint).toMatch(/Retrying with shellEscape: true/);
    });
  }

  it('a plain refusal (shell escape off) still offers restrictedShellEscape first', () => {
    const hint = shellEscapeRefusedHint(PLAIN_REFUSAL, latexmk);
    expect(hint).toMatch(/Retry with restrictedShellEscape: true \(or shellEscape: true\)/);
  });
});

describe('TikZ externalization advice under restricted mode', () => {
  it('the collapsed parseLog error names only shellEscape', () => {
    const errors = parseLog(RESTRICTED_TIKZ_LOG).errors;
    const tikz = errors.filter((e) => /TikZ externalization failed for 2 figures/.test(e.message));
    expect(tikz).toHaveLength(1);
    expect(tikz[0]?.message).not.toMatch(/restrictedShellEscape: true/);
    expect(tikz[0]?.message).toMatch(/Retry compile with shellEscape: true/);
    expect(tikz[0]?.message).toMatch(/restricted to TeX's allow-list/);
  });

  it('tikzShellEscapeHint names shellEscape only, restricted mode on or off', () => {
    const hint = tikzShellEscapeHint;
    const text = hint(RESTRICTED_TIKZ_LOG, { shellEscapeOn: false, backend: 'latexmk' });
    expect(text).toMatch(/Retry compile with shellEscape: true/);
    expect(text).not.toMatch(/preferred/);
    // The same where shell escape was simply off: the allow-list never holds the engine call
    // externalization makes, so restrictedShellEscape is no retry there either.
    const off = RESTRICTED_TIKZ_LOG.replace(' restricted \\write18 enabled.\n', '').replaceAll(
      '...disabled (restricted).',
      '...disabled.',
    );
    const offText = hint(off, { shellEscapeOn: false, backend: 'latexmk' });
    expect(offText).toMatch(/Retry compile with shellEscape: true/);
    expect(offText).not.toMatch(/restrictedShellEscape: true/);
    expect(offText).toMatch(/ARBITRARY shell commands/);
    expect(hint(RESTRICTED_TIKZ_LOG, { shellEscapeOn: true, backend: 'latexmk' })).toBe(undefined);
  });
});

/*
 * `shellEscapeOverriddenHint` (a latexmkrc that turned shell escape back on though the caller left
 * it off) — moved here from `laneC2CompileHints.test.ts` with the function, from the tool layer to
 * `src/services/compiler.ts` beside its siblings.
 */
describe('shellEscapeOverriddenHint', () => {
  const FULL = 'This is pdfTeX, Version 3.14159265\n \\write18 enabled.\n**main.tex\n';
  const RESTRICTED =
    'This is pdfTeX, Version 3.14159265\n restricted \\write18 enabled.\n**main.tex\n';
  const LUA_FULL = 'This is LuaHBTeX, Version 1.24.0\n system commands enabled.\n**main.tex\n';

  it('warns when the log shows shell escape on although the call left it off', () => {
    for (const log of [FULL, LUA_FULL]) {
      const hint = shellEscapeOverriddenHint(log, { shellEscapeOn: false, backend: 'latexmk' });
      expect(hint).toContain("Shell escape was requested off, but the engine's log shows it");
      expect(hint).toContain('a latexmkrc');
      expect(hint).toContain('ARBITRARY');
      expect(hint).not.toContain('restricted');
    }
  });

  it("names restricted mode as such: only the allow-list's helpers could run", () => {
    const hint = shellEscapeOverriddenHint(RESTRICTED, {
      shellEscapeOn: false,
      backend: 'latexmk',
    });
    expect(hint).toContain("enabled (restricted to TeX's allow-list)");
    expect(hint).toContain('allow-listed shell commands');
    expect(hint).not.toContain('ARBITRARY');
  });

  it('says nothing when the caller opted in, the banner is absent, or tectonic ran', () => {
    expect(
      shellEscapeOverriddenHint(FULL, { shellEscapeOn: true, backend: 'latexmk' }),
    ).toBeUndefined();
    expect(
      shellEscapeOverriddenHint('This is pdfTeX\n**main.tex\n', {
        shellEscapeOn: false,
        backend: 'latexmk',
      }),
    ).toBeUndefined();
    // Tectonic reads no latexmkrc: a banner in its log is not one's doing.
    expect(
      shellEscapeOverriddenHint(FULL, { shellEscapeOn: false, backend: 'tectonic' }),
    ).toBeUndefined();
  });
});
